// Code generated by ent, DO NOT EDIT.

package detail

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the detail type in the database.
	Label = "detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldDetailUrl holds the string denoting the detailurl field in the database.
	FieldDetailUrl = "detail_url"
	// FieldPackage holds the string denoting the package field in the database.
	FieldPackage = "package"
	// FieldDownloaded holds the string denoting the downloaded field in the database.
	FieldDownloaded = "downloaded"
	// FieldEpisodes holds the string denoting the episodes field in the database.
	FieldEpisodes = "episodes"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldTrackIds holds the string denoting the track_ids field in the database.
	FieldTrackIds = "track_ids"
	// EdgeTrackers holds the string denoting the trackers edge name in mutations.
	EdgeTrackers = "trackers"
	// Table holds the table name of the detail in the database.
	Table = "details"
	// TrackersTable is the table that holds the trackers relation/edge. The primary key declared below.
	TrackersTable = "detail_trackers"
	// TrackersInverseTable is the table name for the Tracker entity.
	// It exists in this package in order to avoid circular dependency with the "tracker" package.
	TrackersInverseTable = "trackers"
)

// Columns holds all SQL columns for detail fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldCover,
	FieldDesc,
	FieldDetailUrl,
	FieldPackage,
	FieldDownloaded,
	FieldEpisodes,
	FieldHeaders,
	FieldTrackIds,
}

var (
	// TrackersPrimaryKey and TrackersColumn2 are the table columns denoting the
	// primary key for the trackers relation (M2M).
	TrackersPrimaryKey = []string{"detail_id", "tracker_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DetailUrlValidator is a validator for the "detailUrl" field. It is called by the builders before save.
	DetailUrlValidator func(string) error
	// PackageValidator is a validator for the "package" field. It is called by the builders before save.
	PackageValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Detail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByDesc orders the results by the desc field.
func ByDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesc, opts...).ToFunc()
}

// ByDetailUrl orders the results by the detailUrl field.
func ByDetailUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDetailUrl, opts...).ToFunc()
}

// ByPackage orders the results by the package field.
func ByPackage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackage, opts...).ToFunc()
}

// ByEpisodes orders the results by the episodes field.
func ByEpisodes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpisodes, opts...).ToFunc()
}

// ByHeaders orders the results by the headers field.
func ByHeaders(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeaders, opts...).ToFunc()
}

// ByTrackersCount orders the results by trackers count.
func ByTrackersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTrackersStep(), opts...)
	}
}

// ByTrackers orders the results by trackers terms.
func ByTrackers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTrackersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTrackersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TrackersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TrackersTable, TrackersPrimaryKey...),
	)
}
