// Code generated by ent, DO NOT EDIT.

package history

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/miru-project/miru-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.History {
	return predicate.History(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.History {
	return predicate.History(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldID, id))
}

// Package applies equality check predicate on the "package" field. It's identical to PackageEQ.
func Package(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldPackage, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldURL, v))
}

// Cover applies equality check predicate on the "cover" field. It's identical to CoverEQ.
func Cover(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldCover, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldType, v))
}

// EpisodeGroupID applies equality check predicate on the "episode_group_id" field. It's identical to EpisodeGroupIDEQ.
func EpisodeGroupID(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldEpisodeGroupID, v))
}

// EpisodeID applies equality check predicate on the "episode_id" field. It's identical to EpisodeIDEQ.
func EpisodeID(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldEpisodeID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldTitle, v))
}

// EpisodeTitle applies equality check predicate on the "episode_title" field. It's identical to EpisodeTitleEQ.
func EpisodeTitle(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldEpisodeTitle, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldProgress, v))
}

// TotalProgress applies equality check predicate on the "total_progress" field. It's identical to TotalProgressEQ.
func TotalProgress(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldTotalProgress, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.History {
	return predicate.History(sql.FieldEQ(FieldDate, v))
}

// PackageEQ applies the EQ predicate on the "package" field.
func PackageEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldPackage, v))
}

// PackageNEQ applies the NEQ predicate on the "package" field.
func PackageNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldPackage, v))
}

// PackageIn applies the In predicate on the "package" field.
func PackageIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldPackage, vs...))
}

// PackageNotIn applies the NotIn predicate on the "package" field.
func PackageNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldPackage, vs...))
}

// PackageGT applies the GT predicate on the "package" field.
func PackageGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldPackage, v))
}

// PackageGTE applies the GTE predicate on the "package" field.
func PackageGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldPackage, v))
}

// PackageLT applies the LT predicate on the "package" field.
func PackageLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldPackage, v))
}

// PackageLTE applies the LTE predicate on the "package" field.
func PackageLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldPackage, v))
}

// PackageContains applies the Contains predicate on the "package" field.
func PackageContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldPackage, v))
}

// PackageHasPrefix applies the HasPrefix predicate on the "package" field.
func PackageHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldPackage, v))
}

// PackageHasSuffix applies the HasSuffix predicate on the "package" field.
func PackageHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldPackage, v))
}

// PackageEqualFold applies the EqualFold predicate on the "package" field.
func PackageEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldPackage, v))
}

// PackageContainsFold applies the ContainsFold predicate on the "package" field.
func PackageContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldPackage, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldURL, v))
}

// CoverEQ applies the EQ predicate on the "cover" field.
func CoverEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldCover, v))
}

// CoverNEQ applies the NEQ predicate on the "cover" field.
func CoverNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldCover, v))
}

// CoverIn applies the In predicate on the "cover" field.
func CoverIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldCover, vs...))
}

// CoverNotIn applies the NotIn predicate on the "cover" field.
func CoverNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldCover, vs...))
}

// CoverGT applies the GT predicate on the "cover" field.
func CoverGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldCover, v))
}

// CoverGTE applies the GTE predicate on the "cover" field.
func CoverGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldCover, v))
}

// CoverLT applies the LT predicate on the "cover" field.
func CoverLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldCover, v))
}

// CoverLTE applies the LTE predicate on the "cover" field.
func CoverLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldCover, v))
}

// CoverContains applies the Contains predicate on the "cover" field.
func CoverContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldCover, v))
}

// CoverHasPrefix applies the HasPrefix predicate on the "cover" field.
func CoverHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldCover, v))
}

// CoverHasSuffix applies the HasSuffix predicate on the "cover" field.
func CoverHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldCover, v))
}

// CoverIsNil applies the IsNil predicate on the "cover" field.
func CoverIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldCover))
}

// CoverNotNil applies the NotNil predicate on the "cover" field.
func CoverNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldCover))
}

// CoverEqualFold applies the EqualFold predicate on the "cover" field.
func CoverEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldCover, v))
}

// CoverContainsFold applies the ContainsFold predicate on the "cover" field.
func CoverContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldCover, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldType, v))
}

// EpisodeGroupIDEQ applies the EQ predicate on the "episode_group_id" field.
func EpisodeGroupIDEQ(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldEpisodeGroupID, v))
}

// EpisodeGroupIDNEQ applies the NEQ predicate on the "episode_group_id" field.
func EpisodeGroupIDNEQ(v int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldEpisodeGroupID, v))
}

// EpisodeGroupIDIn applies the In predicate on the "episode_group_id" field.
func EpisodeGroupIDIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldEpisodeGroupID, vs...))
}

// EpisodeGroupIDNotIn applies the NotIn predicate on the "episode_group_id" field.
func EpisodeGroupIDNotIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldEpisodeGroupID, vs...))
}

// EpisodeGroupIDGT applies the GT predicate on the "episode_group_id" field.
func EpisodeGroupIDGT(v int) predicate.History {
	return predicate.History(sql.FieldGT(FieldEpisodeGroupID, v))
}

// EpisodeGroupIDGTE applies the GTE predicate on the "episode_group_id" field.
func EpisodeGroupIDGTE(v int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldEpisodeGroupID, v))
}

// EpisodeGroupIDLT applies the LT predicate on the "episode_group_id" field.
func EpisodeGroupIDLT(v int) predicate.History {
	return predicate.History(sql.FieldLT(FieldEpisodeGroupID, v))
}

// EpisodeGroupIDLTE applies the LTE predicate on the "episode_group_id" field.
func EpisodeGroupIDLTE(v int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldEpisodeGroupID, v))
}

// EpisodeIDEQ applies the EQ predicate on the "episode_id" field.
func EpisodeIDEQ(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldEpisodeID, v))
}

// EpisodeIDNEQ applies the NEQ predicate on the "episode_id" field.
func EpisodeIDNEQ(v int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldEpisodeID, v))
}

// EpisodeIDIn applies the In predicate on the "episode_id" field.
func EpisodeIDIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldEpisodeID, vs...))
}

// EpisodeIDNotIn applies the NotIn predicate on the "episode_id" field.
func EpisodeIDNotIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldEpisodeID, vs...))
}

// EpisodeIDGT applies the GT predicate on the "episode_id" field.
func EpisodeIDGT(v int) predicate.History {
	return predicate.History(sql.FieldGT(FieldEpisodeID, v))
}

// EpisodeIDGTE applies the GTE predicate on the "episode_id" field.
func EpisodeIDGTE(v int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldEpisodeID, v))
}

// EpisodeIDLT applies the LT predicate on the "episode_id" field.
func EpisodeIDLT(v int) predicate.History {
	return predicate.History(sql.FieldLT(FieldEpisodeID, v))
}

// EpisodeIDLTE applies the LTE predicate on the "episode_id" field.
func EpisodeIDLTE(v int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldEpisodeID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldTitle, v))
}

// EpisodeTitleEQ applies the EQ predicate on the "episode_title" field.
func EpisodeTitleEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldEpisodeTitle, v))
}

// EpisodeTitleNEQ applies the NEQ predicate on the "episode_title" field.
func EpisodeTitleNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldEpisodeTitle, v))
}

// EpisodeTitleIn applies the In predicate on the "episode_title" field.
func EpisodeTitleIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldEpisodeTitle, vs...))
}

// EpisodeTitleNotIn applies the NotIn predicate on the "episode_title" field.
func EpisodeTitleNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldEpisodeTitle, vs...))
}

// EpisodeTitleGT applies the GT predicate on the "episode_title" field.
func EpisodeTitleGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldEpisodeTitle, v))
}

// EpisodeTitleGTE applies the GTE predicate on the "episode_title" field.
func EpisodeTitleGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldEpisodeTitle, v))
}

// EpisodeTitleLT applies the LT predicate on the "episode_title" field.
func EpisodeTitleLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldEpisodeTitle, v))
}

// EpisodeTitleLTE applies the LTE predicate on the "episode_title" field.
func EpisodeTitleLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldEpisodeTitle, v))
}

// EpisodeTitleContains applies the Contains predicate on the "episode_title" field.
func EpisodeTitleContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldEpisodeTitle, v))
}

// EpisodeTitleHasPrefix applies the HasPrefix predicate on the "episode_title" field.
func EpisodeTitleHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldEpisodeTitle, v))
}

// EpisodeTitleHasSuffix applies the HasSuffix predicate on the "episode_title" field.
func EpisodeTitleHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldEpisodeTitle, v))
}

// EpisodeTitleEqualFold applies the EqualFold predicate on the "episode_title" field.
func EpisodeTitleEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldEpisodeTitle, v))
}

// EpisodeTitleContainsFold applies the ContainsFold predicate on the "episode_title" field.
func EpisodeTitleContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldEpisodeTitle, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldProgress, v))
}

// ProgressContains applies the Contains predicate on the "progress" field.
func ProgressContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldProgress, v))
}

// ProgressHasPrefix applies the HasPrefix predicate on the "progress" field.
func ProgressHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldProgress, v))
}

// ProgressHasSuffix applies the HasSuffix predicate on the "progress" field.
func ProgressHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldProgress, v))
}

// ProgressEqualFold applies the EqualFold predicate on the "progress" field.
func ProgressEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldProgress, v))
}

// ProgressContainsFold applies the ContainsFold predicate on the "progress" field.
func ProgressContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldProgress, v))
}

// TotalProgressEQ applies the EQ predicate on the "total_progress" field.
func TotalProgressEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldTotalProgress, v))
}

// TotalProgressNEQ applies the NEQ predicate on the "total_progress" field.
func TotalProgressNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldTotalProgress, v))
}

// TotalProgressIn applies the In predicate on the "total_progress" field.
func TotalProgressIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldTotalProgress, vs...))
}

// TotalProgressNotIn applies the NotIn predicate on the "total_progress" field.
func TotalProgressNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldTotalProgress, vs...))
}

// TotalProgressGT applies the GT predicate on the "total_progress" field.
func TotalProgressGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldTotalProgress, v))
}

// TotalProgressGTE applies the GTE predicate on the "total_progress" field.
func TotalProgressGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldTotalProgress, v))
}

// TotalProgressLT applies the LT predicate on the "total_progress" field.
func TotalProgressLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldTotalProgress, v))
}

// TotalProgressLTE applies the LTE predicate on the "total_progress" field.
func TotalProgressLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldTotalProgress, v))
}

// TotalProgressContains applies the Contains predicate on the "total_progress" field.
func TotalProgressContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldTotalProgress, v))
}

// TotalProgressHasPrefix applies the HasPrefix predicate on the "total_progress" field.
func TotalProgressHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldTotalProgress, v))
}

// TotalProgressHasSuffix applies the HasSuffix predicate on the "total_progress" field.
func TotalProgressHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldTotalProgress, v))
}

// TotalProgressEqualFold applies the EqualFold predicate on the "total_progress" field.
func TotalProgressEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldTotalProgress, v))
}

// TotalProgressContainsFold applies the ContainsFold predicate on the "total_progress" field.
func TotalProgressContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldTotalProgress, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.History {
	return predicate.History(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.History {
	return predicate.History(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.History {
	return predicate.History(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.History {
	return predicate.History(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.History {
	return predicate.History(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.History {
	return predicate.History(sql.FieldLTE(FieldDate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.History) predicate.History {
	return predicate.History(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.History) predicate.History {
	return predicate.History(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.History) predicate.History {
	return predicate.History(sql.NotPredicates(p))
}
