// Code generated by ent, DO NOT EDIT.

package tracker

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/miru-project/miru-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldID, id))
}

// TrackerID applies equality check predicate on the "tracker_id" field. It's identical to TrackerIDEQ.
func TrackerID(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldTrackerID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldStatus, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldScore, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldProgress, v))
}

// TotalProgress applies equality check predicate on the "total_progress" field. It's identical to TotalProgressEQ.
func TotalProgress(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldTotalProgress, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldStartDate, v))
}

// FinishDate applies equality check predicate on the "finish_date" field. It's identical to FinishDateEQ.
func FinishDate(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldFinishDate, v))
}

// TrackerIDEQ applies the EQ predicate on the "tracker_id" field.
func TrackerIDEQ(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldTrackerID, v))
}

// TrackerIDNEQ applies the NEQ predicate on the "tracker_id" field.
func TrackerIDNEQ(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldTrackerID, v))
}

// TrackerIDIn applies the In predicate on the "tracker_id" field.
func TrackerIDIn(vs ...string) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldTrackerID, vs...))
}

// TrackerIDNotIn applies the NotIn predicate on the "tracker_id" field.
func TrackerIDNotIn(vs ...string) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldTrackerID, vs...))
}

// TrackerIDGT applies the GT predicate on the "tracker_id" field.
func TrackerIDGT(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldTrackerID, v))
}

// TrackerIDGTE applies the GTE predicate on the "tracker_id" field.
func TrackerIDGTE(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldTrackerID, v))
}

// TrackerIDLT applies the LT predicate on the "tracker_id" field.
func TrackerIDLT(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldTrackerID, v))
}

// TrackerIDLTE applies the LTE predicate on the "tracker_id" field.
func TrackerIDLTE(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldTrackerID, v))
}

// TrackerIDContains applies the Contains predicate on the "tracker_id" field.
func TrackerIDContains(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldContains(FieldTrackerID, v))
}

// TrackerIDHasPrefix applies the HasPrefix predicate on the "tracker_id" field.
func TrackerIDHasPrefix(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldHasPrefix(FieldTrackerID, v))
}

// TrackerIDHasSuffix applies the HasSuffix predicate on the "tracker_id" field.
func TrackerIDHasSuffix(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldHasSuffix(FieldTrackerID, v))
}

// TrackerIDEqualFold applies the EqualFold predicate on the "tracker_id" field.
func TrackerIDEqualFold(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldEqualFold(FieldTrackerID, v))
}

// TrackerIDContainsFold applies the ContainsFold predicate on the "tracker_id" field.
func TrackerIDContainsFold(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldContainsFold(FieldTrackerID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldProvider, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Tracker {
	return predicate.Tracker(sql.FieldContainsFold(FieldStatus, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldScore, v))
}

// ScoreIsNil applies the IsNil predicate on the "score" field.
func ScoreIsNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldIsNull(FieldScore))
}

// ScoreNotNil applies the NotNil predicate on the "score" field.
func ScoreNotNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldNotNull(FieldScore))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldProgress, v))
}

// TotalProgressEQ applies the EQ predicate on the "total_progress" field.
func TotalProgressEQ(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldTotalProgress, v))
}

// TotalProgressNEQ applies the NEQ predicate on the "total_progress" field.
func TotalProgressNEQ(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldTotalProgress, v))
}

// TotalProgressIn applies the In predicate on the "total_progress" field.
func TotalProgressIn(vs ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldTotalProgress, vs...))
}

// TotalProgressNotIn applies the NotIn predicate on the "total_progress" field.
func TotalProgressNotIn(vs ...int) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldTotalProgress, vs...))
}

// TotalProgressGT applies the GT predicate on the "total_progress" field.
func TotalProgressGT(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldTotalProgress, v))
}

// TotalProgressGTE applies the GTE predicate on the "total_progress" field.
func TotalProgressGTE(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldTotalProgress, v))
}

// TotalProgressLT applies the LT predicate on the "total_progress" field.
func TotalProgressLT(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldTotalProgress, v))
}

// TotalProgressLTE applies the LTE predicate on the "total_progress" field.
func TotalProgressLTE(v int) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldTotalProgress, v))
}

// TotalProgressIsNil applies the IsNil predicate on the "total_progress" field.
func TotalProgressIsNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldIsNull(FieldTotalProgress))
}

// TotalProgressNotNil applies the NotNil predicate on the "total_progress" field.
func TotalProgressNotNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldNotNull(FieldTotalProgress))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldNotNull(FieldStartDate))
}

// FinishDateEQ applies the EQ predicate on the "finish_date" field.
func FinishDateEQ(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldEQ(FieldFinishDate, v))
}

// FinishDateNEQ applies the NEQ predicate on the "finish_date" field.
func FinishDateNEQ(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldNEQ(FieldFinishDate, v))
}

// FinishDateIn applies the In predicate on the "finish_date" field.
func FinishDateIn(vs ...int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldIn(FieldFinishDate, vs...))
}

// FinishDateNotIn applies the NotIn predicate on the "finish_date" field.
func FinishDateNotIn(vs ...int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldNotIn(FieldFinishDate, vs...))
}

// FinishDateGT applies the GT predicate on the "finish_date" field.
func FinishDateGT(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldGT(FieldFinishDate, v))
}

// FinishDateGTE applies the GTE predicate on the "finish_date" field.
func FinishDateGTE(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldGTE(FieldFinishDate, v))
}

// FinishDateLT applies the LT predicate on the "finish_date" field.
func FinishDateLT(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldLT(FieldFinishDate, v))
}

// FinishDateLTE applies the LTE predicate on the "finish_date" field.
func FinishDateLTE(v int64) predicate.Tracker {
	return predicate.Tracker(sql.FieldLTE(FieldFinishDate, v))
}

// FinishDateIsNil applies the IsNil predicate on the "finish_date" field.
func FinishDateIsNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldIsNull(FieldFinishDate))
}

// FinishDateNotNil applies the NotNil predicate on the "finish_date" field.
func FinishDateNotNil() predicate.Tracker {
	return predicate.Tracker(sql.FieldNotNull(FieldFinishDate))
}

// HasDetails applies the HasEdge predicate on the "details" edge.
func HasDetails() predicate.Tracker {
	return predicate.Tracker(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, DetailsTable, DetailsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDetailsWith applies the HasEdge predicate on the "details" edge with a given conditions (other predicates).
func HasDetailsWith(preds ...predicate.Detail) predicate.Tracker {
	return predicate.Tracker(func(s *sql.Selector) {
		step := newDetailsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tracker) predicate.Tracker {
	return predicate.Tracker(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tracker) predicate.Tracker {
	return predicate.Tracker(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tracker) predicate.Tracker {
	return predicate.Tracker(sql.NotPredicates(p))
}
