// Code generated by ent, DO NOT EDIT.

package track

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the track type in the database.
	Label = "track"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackingID holds the string denoting the tracking_id field in the database.
	FieldTrackingID = "tracking_id"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldMediaType holds the string denoting the media_type field in the database.
	FieldMediaType = "media_type"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// Table holds the table name of the track in the database.
	Table = "tracks"
)

// Columns holds all SQL columns for track fields.
var Columns = []string{
	FieldID,
	FieldTrackingID,
	FieldData,
	FieldMediaType,
	FieldProvider,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Provider defines the type for the "provider" enum field.
type Provider string

// Provider values.
const (
	ProviderTMDB    Provider = "TMDB"
	ProviderAnilist Provider = "Anilist"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderTMDB, ProviderAnilist:
		return nil
	default:
		return fmt.Errorf("track: invalid enum value for provider field: %q", pr)
	}
}

// OrderOption defines the ordering options for the Track queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrackingID orders the results by the tracking_id field.
func ByTrackingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackingID, opts...).ToFunc()
}

// ByData orders the results by the data field.
func ByData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldData, opts...).ToFunc()
}

// ByMediaType orders the results by the media_type field.
func ByMediaType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaType, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}
