// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppSettingsColumns holds the columns for the "app_settings" table.
	AppSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString},
	}
	// AppSettingsTable holds the schema information for the "app_settings" table.
	AppSettingsTable = &schema.Table{
		Name:       "app_settings",
		Columns:    AppSettingsColumns,
		PrimaryKey: []*schema.Column{AppSettingsColumns[0]},
	}
	// DetailsColumns holds the columns for the "details" table.
	DetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "desc", Type: field.TypeString, Nullable: true},
		{Name: "detail_url", Type: field.TypeString},
		{Name: "package", Type: field.TypeString},
		{Name: "downloaded", Type: field.TypeJSON, Nullable: true},
		{Name: "episodes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "headers", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// DetailsTable holds the schema information for the "details" table.
	DetailsTable = &schema.Table{
		Name:       "details",
		Columns:    DetailsColumns,
		PrimaryKey: []*schema.Column{DetailsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "detail_package_detail_url",
				Unique:  true,
				Columns: []*schema.Column{DetailsColumns[5], DetailsColumns[4]},
			},
		},
	}
	// ExtensionsColumns holds the columns for the "extensions" table.
	ExtensionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ExtensionsTable holds the schema information for the "extensions" table.
	ExtensionsTable = &schema.Table{
		Name:       "extensions",
		Columns:    ExtensionsColumns,
		PrimaryKey: []*schema.Column{ExtensionsColumns[0]},
	}
	// ExtensionRepoSettingsColumns holds the columns for the "extension_repo_settings" table.
	ExtensionRepoSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "link", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// ExtensionRepoSettingsTable holds the schema information for the "extension_repo_settings" table.
	ExtensionRepoSettingsTable = &schema.Table{
		Name:       "extension_repo_settings",
		Columns:    ExtensionRepoSettingsColumns,
		PrimaryKey: []*schema.Column{ExtensionRepoSettingsColumns[0]},
	}
	// ExtensionSettingsColumns holds the columns for the "extension_settings" table.
	ExtensionSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Nullable: true},
		{Name: "default_value", Type: field.TypeString, Default: ""},
		{Name: "db_type", Type: field.TypeEnum, Enums: []string{"input", "radio", "toggle"}, Default: "input"},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "options", Type: field.TypeString, Nullable: true},
	}
	// ExtensionSettingsTable holds the schema information for the "extension_settings" table.
	ExtensionSettingsTable = &schema.Table{
		Name:       "extension_settings",
		Columns:    ExtensionSettingsColumns,
		PrimaryKey: []*schema.Column{ExtensionSettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_extension_setting_package_key",
				Unique:  true,
				Columns: []*schema.Column{ExtensionSettingsColumns[1], ExtensionSettingsColumns[3]},
			},
		},
	}
	// FavoritesColumns holds the columns for the "favorites" table.
	FavoritesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "date", Type: field.TypeTime},
	}
	// FavoritesTable holds the schema information for the "favorites" table.
	FavoritesTable = &schema.Table{
		Name:       "favorites",
		Columns:    FavoritesColumns,
		PrimaryKey: []*schema.Column{FavoritesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "favorite_package_url",
				Unique:  true,
				Columns: []*schema.Column{FavoritesColumns[1], FavoritesColumns[2]},
			},
		},
	}
	// FavoriteGroupsColumns holds the columns for the "favorite_groups" table.
	FavoriteGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "date", Type: field.TypeTime},
	}
	// FavoriteGroupsTable holds the schema information for the "favorite_groups" table.
	FavoriteGroupsTable = &schema.Table{
		Name:       "favorite_groups",
		Columns:    FavoriteGroupsColumns,
		PrimaryKey: []*schema.Column{FavoriteGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "favoritegroup_name",
				Unique:  true,
				Columns: []*schema.Column{FavoriteGroupsColumns[1]},
			},
		},
	}
	// HistoriesColumns holds the columns for the "histories" table.
	HistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "detail_url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString},
		{Name: "episode_group_id", Type: field.TypeInt},
		{Name: "episode_id", Type: field.TypeInt},
		{Name: "title", Type: field.TypeString},
		{Name: "episode_title", Type: field.TypeString},
		{Name: "progress", Type: field.TypeInt},
		{Name: "total_progress", Type: field.TypeInt},
		{Name: "date", Type: field.TypeTime},
	}
	// HistoriesTable holds the schema information for the "histories" table.
	HistoriesTable = &schema.Table{
		Name:       "histories",
		Columns:    HistoriesColumns,
		PrimaryKey: []*schema.Column{HistoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "history_package_url",
				Unique:  true,
				Columns: []*schema.Column{HistoriesColumns[1], HistoriesColumns[2]},
			},
		},
	}
	// FavoriteGroupFavoritesColumns holds the columns for the "favorite_group_favorites" table.
	FavoriteGroupFavoritesColumns = []*schema.Column{
		{Name: "favorite_group_id", Type: field.TypeInt},
		{Name: "favorite_id", Type: field.TypeInt},
	}
	// FavoriteGroupFavoritesTable holds the schema information for the "favorite_group_favorites" table.
	FavoriteGroupFavoritesTable = &schema.Table{
		Name:       "favorite_group_favorites",
		Columns:    FavoriteGroupFavoritesColumns,
		PrimaryKey: []*schema.Column{FavoriteGroupFavoritesColumns[0], FavoriteGroupFavoritesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "favorite_group_favorites_favorite_group_id",
				Columns:    []*schema.Column{FavoriteGroupFavoritesColumns[0]},
				RefColumns: []*schema.Column{FavoriteGroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "favorite_group_favorites_favorite_id",
				Columns:    []*schema.Column{FavoriteGroupFavoritesColumns[1]},
				RefColumns: []*schema.Column{FavoritesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppSettingsTable,
		DetailsTable,
		ExtensionsTable,
		ExtensionRepoSettingsTable,
		ExtensionSettingsTable,
		FavoritesTable,
		FavoriteGroupsTable,
		HistoriesTable,
		FavoriteGroupFavoritesTable,
	}
)

func init() {
	FavoriteGroupFavoritesTable.ForeignKeys[0].RefTable = FavoriteGroupsTable
	FavoriteGroupFavoritesTable.ForeignKeys[1].RefTable = FavoritesTable
}
