syntax = "proto3";

package miru;

import "proto/common.proto";
import "proto/db_model.proto";

option go_package = "github.com/miru-project/miru-core/proto";

message WatchEventsRequest {}

message WatchEventsResponse {
  oneof event {
    DownloadEvent download_event = 1;
    ExtensionEvent extension_event = 2;
    HistoryEvent history_event = 3;
    DevLogEvent dev_log_event = 4;
    DevNetworkEvent dev_network_event = 5;
  }
}

message DownloadEvent { map<int32, DownloadProgress> download_status = 1; }

message ExtensionEvent { repeated ExtensionMeta extension_meta = 1; }

message HistoryEvent { repeated History history = 1; }

message DevLogEvent {
  string package = 1;
  string message = 2;
  string level = 3;
  int64 timestamp = 4;
}

message DevNetworkEvent {
  string package = 1;
  string url = 2;
  string method = 3;
  int32 status = 4;
  int64 duration = 5;
  int64 timestamp = 6;
  string request_headers = 7;
  string request_body = 8;
  string response_headers = 9;
  string response_body = 10;
}

service EventService {
  rpc WatchEvents(WatchEventsRequest) returns (stream WatchEventsResponse);
}
