// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/miru-project/miru-core/ent/appsetting"
)

// AppSetting is the model entity for the AppSetting schema.
type AppSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key
	Key string `json:"key,omitempty"`
	// Value
	Value        string `json:"value,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case appsetting.FieldID:
			values[i] = new(sql.NullInt64)
		case appsetting.FieldKey, appsetting.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppSetting fields.
func (as *AppSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			as.ID = int(value.Int64)
		case appsetting.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				as.Key = value.String
			}
		case appsetting.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				as.Value = value.String
			}
		default:
			as.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the AppSetting.
// This includes values selected through modifiers, order, etc.
func (as *AppSetting) GetValue(name string) (ent.Value, error) {
	return as.selectValues.Get(name)
}

// Update returns a builder for updating this AppSetting.
// Note that you need to call AppSetting.Unwrap() before calling this method if this AppSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (as *AppSetting) Update() *AppSettingUpdateOne {
	return NewAppSettingClient(as.config).UpdateOne(as)
}

// Unwrap unwraps the AppSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (as *AppSetting) Unwrap() *AppSetting {
	_tx, ok := as.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppSetting is not a transactional entity")
	}
	as.config.driver = _tx.drv
	return as
}

// String implements the fmt.Stringer.
func (as *AppSetting) String() string {
	var builder strings.Builder
	builder.WriteString("AppSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", as.ID))
	builder.WriteString("key=")
	builder.WriteString(as.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(as.Value)
	builder.WriteByte(')')
	return builder.String()
}

// AppSettings is a parsable slice of AppSetting.
type AppSettings []*AppSetting
