// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/miru-project/miru-core/ent/extensionreposetting"
)

// ExtensionRepoSettingCreate is the builder for creating a ExtensionRepoSetting entity.
type ExtensionRepoSettingCreate struct {
	config
	mutation *ExtensionRepoSettingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLink sets the "link" field.
func (_c *ExtensionRepoSettingCreate) SetLink(v string) *ExtensionRepoSettingCreate {
	_c.mutation.SetLink(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ExtensionRepoSettingCreate) SetName(v string) *ExtensionRepoSettingCreate {
	_c.mutation.SetName(v)
	return _c
}

// Mutation returns the ExtensionRepoSettingMutation object of the builder.
func (_c *ExtensionRepoSettingCreate) Mutation() *ExtensionRepoSettingMutation {
	return _c.mutation
}

// Save creates the ExtensionRepoSetting in the database.
func (_c *ExtensionRepoSettingCreate) Save(ctx context.Context) (*ExtensionRepoSetting, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExtensionRepoSettingCreate) SaveX(ctx context.Context) *ExtensionRepoSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtensionRepoSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtensionRepoSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExtensionRepoSettingCreate) check() error {
	if _, ok := _c.mutation.Link(); !ok {
		return &ValidationError{Name: "link", err: errors.New(`ent: missing required field "ExtensionRepoSetting.link"`)}
	}
	if v, ok := _c.mutation.Link(); ok {
		if err := extensionreposetting.LinkValidator(v); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "ExtensionRepoSetting.link": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ExtensionRepoSetting.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := extensionreposetting.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ExtensionRepoSetting.name": %w`, err)}
		}
	}
	return nil
}

func (_c *ExtensionRepoSettingCreate) sqlSave(ctx context.Context) (*ExtensionRepoSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExtensionRepoSettingCreate) createSpec() (*ExtensionRepoSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &ExtensionRepoSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(extensionreposetting.Table, sqlgraph.NewFieldSpec(extensionreposetting.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Link(); ok {
		_spec.SetField(extensionreposetting.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(extensionreposetting.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtensionRepoSetting.Create().
//		SetLink(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtensionRepoSettingUpsert) {
//			SetLink(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtensionRepoSettingCreate) OnConflict(opts ...sql.ConflictOption) *ExtensionRepoSettingUpsertOne {
	_c.conflict = opts
	return &ExtensionRepoSettingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtensionRepoSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtensionRepoSettingCreate) OnConflictColumns(columns ...string) *ExtensionRepoSettingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtensionRepoSettingUpsertOne{
		create: _c,
	}
}

type (
	// ExtensionRepoSettingUpsertOne is the builder for "upsert"-ing
	//  one ExtensionRepoSetting node.
	ExtensionRepoSettingUpsertOne struct {
		create *ExtensionRepoSettingCreate
	}

	// ExtensionRepoSettingUpsert is the "OnConflict" setter.
	ExtensionRepoSettingUpsert struct {
		*sql.UpdateSet
	}
)

// SetLink sets the "link" field.
func (u *ExtensionRepoSettingUpsert) SetLink(v string) *ExtensionRepoSettingUpsert {
	u.Set(extensionreposetting.FieldLink, v)
	return u
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *ExtensionRepoSettingUpsert) UpdateLink() *ExtensionRepoSettingUpsert {
	u.SetExcluded(extensionreposetting.FieldLink)
	return u
}

// SetName sets the "name" field.
func (u *ExtensionRepoSettingUpsert) SetName(v string) *ExtensionRepoSettingUpsert {
	u.Set(extensionreposetting.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExtensionRepoSettingUpsert) UpdateName() *ExtensionRepoSettingUpsert {
	u.SetExcluded(extensionreposetting.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ExtensionRepoSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExtensionRepoSettingUpsertOne) UpdateNewValues() *ExtensionRepoSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtensionRepoSetting.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExtensionRepoSettingUpsertOne) Ignore() *ExtensionRepoSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtensionRepoSettingUpsertOne) DoNothing() *ExtensionRepoSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtensionRepoSettingCreate.OnConflict
// documentation for more info.
func (u *ExtensionRepoSettingUpsertOne) Update(set func(*ExtensionRepoSettingUpsert)) *ExtensionRepoSettingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtensionRepoSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetLink sets the "link" field.
func (u *ExtensionRepoSettingUpsertOne) SetLink(v string) *ExtensionRepoSettingUpsertOne {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *ExtensionRepoSettingUpsertOne) UpdateLink() *ExtensionRepoSettingUpsertOne {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.UpdateLink()
	})
}

// SetName sets the "name" field.
func (u *ExtensionRepoSettingUpsertOne) SetName(v string) *ExtensionRepoSettingUpsertOne {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExtensionRepoSettingUpsertOne) UpdateName() *ExtensionRepoSettingUpsertOne {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *ExtensionRepoSettingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtensionRepoSettingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtensionRepoSettingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExtensionRepoSettingUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExtensionRepoSettingUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExtensionRepoSettingCreateBulk is the builder for creating many ExtensionRepoSetting entities in bulk.
type ExtensionRepoSettingCreateBulk struct {
	config
	err      error
	builders []*ExtensionRepoSettingCreate
	conflict []sql.ConflictOption
}

// Save creates the ExtensionRepoSetting entities in the database.
func (_c *ExtensionRepoSettingCreateBulk) Save(ctx context.Context) ([]*ExtensionRepoSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExtensionRepoSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtensionRepoSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExtensionRepoSettingCreateBulk) SaveX(ctx context.Context) []*ExtensionRepoSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtensionRepoSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtensionRepoSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtensionRepoSetting.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtensionRepoSettingUpsert) {
//			SetLink(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtensionRepoSettingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExtensionRepoSettingUpsertBulk {
	_c.conflict = opts
	return &ExtensionRepoSettingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtensionRepoSetting.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtensionRepoSettingCreateBulk) OnConflictColumns(columns ...string) *ExtensionRepoSettingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtensionRepoSettingUpsertBulk{
		create: _c,
	}
}

// ExtensionRepoSettingUpsertBulk is the builder for "upsert"-ing
// a bulk of ExtensionRepoSetting nodes.
type ExtensionRepoSettingUpsertBulk struct {
	create *ExtensionRepoSettingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExtensionRepoSetting.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExtensionRepoSettingUpsertBulk) UpdateNewValues() *ExtensionRepoSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtensionRepoSetting.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExtensionRepoSettingUpsertBulk) Ignore() *ExtensionRepoSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtensionRepoSettingUpsertBulk) DoNothing() *ExtensionRepoSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtensionRepoSettingCreateBulk.OnConflict
// documentation for more info.
func (u *ExtensionRepoSettingUpsertBulk) Update(set func(*ExtensionRepoSettingUpsert)) *ExtensionRepoSettingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtensionRepoSettingUpsert{UpdateSet: update})
	}))
	return u
}

// SetLink sets the "link" field.
func (u *ExtensionRepoSettingUpsertBulk) SetLink(v string) *ExtensionRepoSettingUpsertBulk {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *ExtensionRepoSettingUpsertBulk) UpdateLink() *ExtensionRepoSettingUpsertBulk {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.UpdateLink()
	})
}

// SetName sets the "name" field.
func (u *ExtensionRepoSettingUpsertBulk) SetName(v string) *ExtensionRepoSettingUpsertBulk {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExtensionRepoSettingUpsertBulk) UpdateName() *ExtensionRepoSettingUpsertBulk {
	return u.Update(func(s *ExtensionRepoSettingUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *ExtensionRepoSettingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExtensionRepoSettingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtensionRepoSettingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtensionRepoSettingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
