// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/miru-project/miru-core/ent/extensionrepo"
	"github.com/miru-project/miru-core/ent/predicate"
)

// ExtensionRepoDelete is the builder for deleting a ExtensionRepo entity.
type ExtensionRepoDelete struct {
	config
	hooks    []Hook
	mutation *ExtensionRepoMutation
}

// Where appends a list predicates to the ExtensionRepoDelete builder.
func (_d *ExtensionRepoDelete) Where(ps ...predicate.ExtensionRepo) *ExtensionRepoDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExtensionRepoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExtensionRepoDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExtensionRepoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(extensionrepo.Table, sqlgraph.NewFieldSpec(extensionrepo.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExtensionRepoDeleteOne is the builder for deleting a single ExtensionRepo entity.
type ExtensionRepoDeleteOne struct {
	_d *ExtensionRepoDelete
}

// Where appends a list predicates to the ExtensionRepoDelete builder.
func (_d *ExtensionRepoDeleteOne) Where(ps ...predicate.ExtensionRepo) *ExtensionRepoDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExtensionRepoDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{extensionrepo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExtensionRepoDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
