// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/app_setting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSetting) Reset() {
	*x = AppSetting{}
	mi := &file_proto_app_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSetting) ProtoMessage() {}

func (x *AppSetting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSetting.ProtoReflect.Descriptor instead.
func (*AppSetting) Descriptor() ([]byte, []int) {
	return file_proto_app_setting_proto_rawDescGZIP(), []int{0}
}

func (x *AppSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AppSetting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetAppSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSettingRequest) Reset() {
	*x = GetAppSettingRequest{}
	mi := &file_proto_app_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSettingRequest) ProtoMessage() {}

func (x *GetAppSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSettingRequest.ProtoReflect.Descriptor instead.
func (*GetAppSettingRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_setting_proto_rawDescGZIP(), []int{1}
}

type GetAppSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*AppSetting          `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSettingResponse) Reset() {
	*x = GetAppSettingResponse{}
	mi := &file_proto_app_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSettingResponse) ProtoMessage() {}

func (x *GetAppSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSettingResponse.ProtoReflect.Descriptor instead.
func (*GetAppSettingResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_setting_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppSettingResponse) GetSettings() []*AppSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetAppSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*AppSetting          `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppSettingRequest) Reset() {
	*x = SetAppSettingRequest{}
	mi := &file_proto_app_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppSettingRequest) ProtoMessage() {}

func (x *SetAppSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppSettingRequest.ProtoReflect.Descriptor instead.
func (*SetAppSettingRequest) Descriptor() ([]byte, []int) {
	return file_proto_app_setting_proto_rawDescGZIP(), []int{3}
}

func (x *SetAppSettingRequest) GetSettings() []*AppSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SetAppSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppSettingResponse) Reset() {
	*x = SetAppSettingResponse{}
	mi := &file_proto_app_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppSettingResponse) ProtoMessage() {}

func (x *SetAppSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppSettingResponse.ProtoReflect.Descriptor instead.
func (*SetAppSettingResponse) Descriptor() ([]byte, []int) {
	return file_proto_app_setting_proto_rawDescGZIP(), []int{4}
}

func (x *SetAppSettingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_app_setting_proto protoreflect.FileDescriptor

const file_proto_app_setting_proto_rawDesc = "" +
	"\n" +
	"\x17proto/app_setting.proto\x12\x04miru\"4\n" +
	"\n" +
	"AppSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x16\n" +
	"\x14GetAppSettingRequest\"E\n" +
	"\x15GetAppSettingResponse\x12,\n" +
	"\bsettings\x18\x01 \x03(\v2\x10.miru.AppSettingR\bsettings\"D\n" +
	"\x14SetAppSettingRequest\x12,\n" +
	"\bsettings\x18\x01 \x03(\v2\x10.miru.AppSettingR\bsettings\"1\n" +
	"\x15SetAppSettingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa7\x01\n" +
	"\x11AppSettingService\x12H\n" +
	"\rGetAppSetting\x12\x1a.miru.GetAppSettingRequest\x1a\x1b.miru.GetAppSettingResponse\x12H\n" +
	"\rSetAppSetting\x12\x1a.miru.SetAppSettingRequest\x1a\x1b.miru.SetAppSettingResponseB)Z'github.com/miru-project/miru-core/protob\x06proto3"

var (
	file_proto_app_setting_proto_rawDescOnce sync.Once
	file_proto_app_setting_proto_rawDescData []byte
)

func file_proto_app_setting_proto_rawDescGZIP() []byte {
	file_proto_app_setting_proto_rawDescOnce.Do(func() {
		file_proto_app_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_app_setting_proto_rawDesc), len(file_proto_app_setting_proto_rawDesc)))
	})
	return file_proto_app_setting_proto_rawDescData
}

var file_proto_app_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_app_setting_proto_goTypes = []any{
	(*AppSetting)(nil),            // 0: miru.AppSetting
	(*GetAppSettingRequest)(nil),  // 1: miru.GetAppSettingRequest
	(*GetAppSettingResponse)(nil), // 2: miru.GetAppSettingResponse
	(*SetAppSettingRequest)(nil),  // 3: miru.SetAppSettingRequest
	(*SetAppSettingResponse)(nil), // 4: miru.SetAppSettingResponse
}
var file_proto_app_setting_proto_depIdxs = []int32{
	0, // 0: miru.GetAppSettingResponse.settings:type_name -> miru.AppSetting
	0, // 1: miru.SetAppSettingRequest.settings:type_name -> miru.AppSetting
	1, // 2: miru.AppSettingService.GetAppSetting:input_type -> miru.GetAppSettingRequest
	3, // 3: miru.AppSettingService.SetAppSetting:input_type -> miru.SetAppSettingRequest
	2, // 4: miru.AppSettingService.GetAppSetting:output_type -> miru.GetAppSettingResponse
	4, // 5: miru.AppSettingService.SetAppSetting:output_type -> miru.SetAppSettingResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_app_setting_proto_init() }
func file_proto_app_setting_proto_init() {
	if File_proto_app_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_app_setting_proto_rawDesc), len(file_proto_app_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_setting_proto_goTypes,
		DependencyIndexes: file_proto_app_setting_proto_depIdxs,
		MessageInfos:      file_proto_app_setting_proto_msgTypes,
	}.Build()
	File_proto_app_setting_proto = out.File
	file_proto_app_setting_proto_goTypes = nil
	file_proto_app_setting_proto_depIdxs = nil
}
