// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	License       string                 `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Lang          string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Package       string                 `protobuf:"bytes,7,opt,name=package,proto3" json:"package,omitempty"`
	WebSite       string                 `protobuf:"bytes,8,opt,name=webSite,proto3" json:"webSite,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Api           string                 `protobuf:"bytes,11,opt,name=api,proto3" json:"api,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	Type          string                 `protobuf:"bytes,13,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionMeta) Reset() {
	*x = ExtensionMeta{}
	mi := &file_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMeta) ProtoMessage() {}

func (x *ExtensionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMeta.ProtoReflect.Descriptor instead.
func (*ExtensionMeta) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ExtensionMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ExtensionMeta) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ExtensionMeta) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *ExtensionMeta) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *ExtensionMeta) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ExtensionMeta) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ExtensionMeta) GetWebSite() string {
	if x != nil {
		return x.WebSite
	}
	return ""
}

func (x *ExtensionMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExtensionMeta) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ExtensionMeta) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ExtensionMeta) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExtensionMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DownloadProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Progress           int32                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Names              []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Total              int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	MediaType          string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	CurrentDownloading string                 `protobuf:"bytes,6,opt,name=current_downloading,json=currentDownloading,proto3" json:"current_downloading,omitempty"`
	TaskId             int32                  `protobuf:"varint,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title              string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Package            string                 `protobuf:"bytes,9,opt,name=package,proto3" json:"package,omitempty"`
	Key                string                 `protobuf:"bytes,10,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadProgress) Reset() {
	*x = DownloadProgress{}
	mi := &file_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgress) ProtoMessage() {}

func (x *DownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgress.ProtoReflect.Descriptor instead.
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DownloadProgress) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *DownloadProgress) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DownloadProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadProgress) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *DownloadProgress) GetCurrentDownloading() string {
	if x != nil {
		return x.CurrentDownloading
	}
	return ""
}

func (x *DownloadProgress) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *DownloadProgress) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DownloadProgress) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *DownloadProgress) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TorrentStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalDown     int64                  `protobuf:"varint,1,opt,name=total_down,json=totalDown,proto3" json:"total_down,omitempty"`
	TotalUp       int64                  `protobuf:"varint,2,opt,name=total_up,json=totalUp,proto3" json:"total_up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentStats) Reset() {
	*x = TorrentStats{}
	mi := &file_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentStats) ProtoMessage() {}

func (x *TorrentStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentStats.ProtoReflect.Descriptor instead.
func (*TorrentStats) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *TorrentStats) GetTotalDown() int64 {
	if x != nil {
		return x.TotalDown
	}
	return 0
}

func (x *TorrentStats) GetTotalUp() int64 {
	if x != nil {
		return x.TotalUp
	}
	return 0
}

type AvailableHlsVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolution    string                 `protobuf:"bytes,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Codec         string                 `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableHlsVariant) Reset() {
	*x = AvailableHlsVariant{}
	mi := &file_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableHlsVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableHlsVariant) ProtoMessage() {}

func (x *AvailableHlsVariant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableHlsVariant.ProtoReflect.Descriptor instead.
func (*AvailableHlsVariant) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *AvailableHlsVariant) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *AvailableHlsVariant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AvailableHlsVariant) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

// Download
type Download struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           []string               `protobuf:"bytes,2,rep,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Package       string                 `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	Progress      []int32                `protobuf:"varint,5,rep,packed,name=progress,proto3" json:"progress,omitempty"`
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	MediaType     string                 `protobuf:"bytes,8,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	SavePath      string                 `protobuf:"bytes,10,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Date          string                 `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,12,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	DetailUrl     string                 `protobuf:"bytes,13,opt,name=detail_url,json=detailUrl,proto3" json:"detail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Download) Reset() {
	*x = Download{}
	mi := &file_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Download) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Download) ProtoMessage() {}

func (x *Download) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Download.ProtoReflect.Descriptor instead.
func (*Download) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *Download) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Download) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *Download) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Download) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Download) GetProgress() []int32 {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *Download) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Download) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Download) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Download) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Download) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *Download) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Download) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *Download) GetDetailUrl() string {
	if x != nil {
		return x.DetailUrl
	}
	return ""
}

// Torrent
type TorrentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Files         []string               `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentResult) Reset() {
	*x = TorrentResult{}
	mi := &file_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentResult) ProtoMessage() {}

func (x *TorrentResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentResult.ProtoReflect.Descriptor instead.
func (*TorrentResult) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *TorrentResult) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *TorrentResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TorrentResult) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_common_proto protoreflect.FileDescriptor

const file_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x12proto/common.proto\x12\x04miru\"\xbd\x02\n" +
	"\rExtensionMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\x04 \x01(\tR\alicense\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x18\n" +
	"\apackage\x18\a \x01(\tR\apackage\x12\x18\n" +
	"\awebSite\x18\b \x01(\tR\awebSite\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x10\n" +
	"\x03api\x18\v \x01(\tR\x03api\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12\x12\n" +
	"\x04type\x18\r \x01(\tR\x04type\"\x9d\x02\n" +
	"\x10DownloadProgress\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12/\n" +
	"\x13current_downloading\x18\x06 \x01(\tR\x12currentDownloading\x12\x17\n" +
	"\atask_id\x18\a \x01(\x05R\x06taskId\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x18\n" +
	"\apackage\x18\t \x01(\tR\apackage\x12\x10\n" +
	"\x03key\x18\n" +
	" \x01(\tR\x03key\"H\n" +
	"\fTorrentStats\x12\x1d\n" +
	"\n" +
	"total_down\x18\x01 \x01(\x03R\ttotalDown\x12\x19\n" +
	"\btotal_up\x18\x02 \x01(\x03R\atotalUp\"]\n" +
	"\x13AvailableHlsVariant\x12\x1e\n" +
	"\n" +
	"resolution\x18\x01 \x01(\tR\n" +
	"resolution\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codec\"\xa7\x03\n" +
	"\bDownload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x03(\tR\x03url\x125\n" +
	"\aheaders\x18\x03 \x03(\v2\x1b.miru.Download.HeadersEntryR\aheaders\x12\x18\n" +
	"\apackage\x18\x04 \x01(\tR\apackage\x12\x1a\n" +
	"\bprogress\x18\x05 \x03(\x05R\bprogress\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"media_type\x18\b \x01(\tR\tmediaType\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1b\n" +
	"\tsave_path\x18\n" +
	" \x01(\tR\bsavePath\x12\x12\n" +
	"\x04date\x18\v \x01(\tR\x04date\x12!\n" +
	"\fdownload_url\x18\f \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"detail_url\x18\r \x01(\tR\tdetailUrl\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\rTorrentResult\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\tR\binfoHash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05filesB)Z'github.com/miru-project/miru-core/protob\x06proto3"

var (
	file_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_rawDescData []byte
)

func file_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)))
	})
	return file_proto_common_proto_rawDescData
}

var file_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_common_proto_goTypes = []any{
	(*ExtensionMeta)(nil),       // 0: miru.ExtensionMeta
	(*DownloadProgress)(nil),    // 1: miru.DownloadProgress
	(*TorrentStats)(nil),        // 2: miru.TorrentStats
	(*AvailableHlsVariant)(nil), // 3: miru.AvailableHlsVariant
	(*Download)(nil),            // 4: miru.Download
	(*TorrentResult)(nil),       // 5: miru.TorrentResult
	nil,                         // 6: miru.Download.HeadersEntry
}
var file_proto_common_proto_depIdxs = []int32{
	6, // 0: miru.Download.headers:type_name -> miru.Download.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_common_proto_init() }
func file_proto_common_proto_init() {
	if File_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_proto_rawDesc), len(file_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_depIdxs,
		MessageInfos:      file_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto = out.File
	file_proto_common_proto_goTypes = nil
	file_proto_common_proto_depIdxs = nil
}
