// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/db.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DbService_GetDetail_FullMethodName                       = "/miru.DbService/GetDetail"
	DbService_UpsertDetail_FullMethodName                    = "/miru.DbService/UpsertDetail"
	DbService_GetAllFavorite_FullMethodName                  = "/miru.DbService/GetAllFavorite"
	DbService_GetFavoriteByPackageAndUrl_FullMethodName      = "/miru.DbService/GetFavoriteByPackageAndUrl"
	DbService_PutFavoriteByIndex_FullMethodName              = "/miru.DbService/PutFavoriteByIndex"
	DbService_PutFavorite_FullMethodName                     = "/miru.DbService/PutFavorite"
	DbService_DeleteFavorite_FullMethodName                  = "/miru.DbService/DeleteFavorite"
	DbService_GetFavoriteGroupsById_FullMethodName           = "/miru.DbService/GetFavoriteGroupsById"
	DbService_GetAllFavoriteGroup_FullMethodName             = "/miru.DbService/GetAllFavoriteGroup"
	DbService_PutFavoriteGroup_FullMethodName                = "/miru.DbService/PutFavoriteGroup"
	DbService_RenameFavoriteGroup_FullMethodName             = "/miru.DbService/RenameFavoriteGroup"
	DbService_DeleteFavoriteGroup_FullMethodName             = "/miru.DbService/DeleteFavoriteGroup"
	DbService_GetFavoriteGroupsByFavorite_FullMethodName     = "/miru.DbService/GetFavoriteGroupsByFavorite"
	DbService_GetHistoriesByType_FullMethodName              = "/miru.DbService/GetHistoriesByType"
	DbService_GetHistoryByPackageAndDetailUrl_FullMethodName = "/miru.DbService/GetHistoryByPackageAndDetailUrl"
	DbService_PutHistory_FullMethodName                      = "/miru.DbService/PutHistory"
	DbService_DeleteHistoryByPackageAndUrl_FullMethodName    = "/miru.DbService/DeleteHistoryByPackageAndUrl"
	DbService_DeleteAllHistory_FullMethodName                = "/miru.DbService/DeleteAllHistory"
	DbService_GetHistorysFiltered_FullMethodName             = "/miru.DbService/GetHistorysFiltered"
)

// DbServiceClient is the client API for DbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbServiceClient interface {
	// Detail
	GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
	UpsertDetail(ctx context.Context, in *UpsertDetailRequest, opts ...grpc.CallOption) (*UpsertDetailResponse, error)
	// Favorite
	GetAllFavorite(ctx context.Context, in *GetAllFavoriteRequest, opts ...grpc.CallOption) (*GetAllFavoriteResponse, error)
	GetFavoriteByPackageAndUrl(ctx context.Context, in *GetFavoriteByPackageAndUrlRequest, opts ...grpc.CallOption) (*GetFavoriteByPackageAndUrlResponse, error)
	PutFavoriteByIndex(ctx context.Context, in *PutFavoriteByIndexRequest, opts ...grpc.CallOption) (*PutFavoriteByIndexResponse, error)
	PutFavorite(ctx context.Context, in *PutFavoriteRequest, opts ...grpc.CallOption) (*PutFavoriteResponse, error)
	DeleteFavorite(ctx context.Context, in *DeleteFavoriteRequest, opts ...grpc.CallOption) (*DeleteFavoriteResponse, error)
	// Favorite Group
	GetFavoriteGroupsById(ctx context.Context, in *GetFavoriteGroupsByIdRequest, opts ...grpc.CallOption) (*GetFavoriteGroupsByIdResponse, error)
	GetAllFavoriteGroup(ctx context.Context, in *GetAllFavoriteGroupRequest, opts ...grpc.CallOption) (*GetAllFavoriteGroupResponse, error)
	PutFavoriteGroup(ctx context.Context, in *PutFavoriteGroupRequest, opts ...grpc.CallOption) (*PutFavoriteGroupResponse, error)
	RenameFavoriteGroup(ctx context.Context, in *RenameFavoriteGroupRequest, opts ...grpc.CallOption) (*RenameFavoriteGroupResponse, error)
	DeleteFavoriteGroup(ctx context.Context, in *DeleteFavoriteGroupRequest, opts ...grpc.CallOption) (*DeleteFavoriteGroupResponse, error)
	GetFavoriteGroupsByFavorite(ctx context.Context, in *GetFavoriteGroupsByFavoriteRequest, opts ...grpc.CallOption) (*GetFavoriteGroupsByFavoriteResponse, error)
	// History
	GetHistoriesByType(ctx context.Context, in *GetHistoriesByTypeRequest, opts ...grpc.CallOption) (*GetHistoriesByTypeResponse, error)
	GetHistoryByPackageAndDetailUrl(ctx context.Context, in *GetHistoryByPackageAndDetailUrlRequest, opts ...grpc.CallOption) (*GetHistoryByPackageAndDetailUrlResponse, error)
	PutHistory(ctx context.Context, in *PutHistoryRequest, opts ...grpc.CallOption) (*PutHistoryResponse, error)
	DeleteHistoryByPackageAndUrl(ctx context.Context, in *DeleteHistoryByPackageAndUrlRequest, opts ...grpc.CallOption) (*DeleteHistoryByPackageAndUrlResponse, error)
	DeleteAllHistory(ctx context.Context, in *DeleteAllHistoryRequest, opts ...grpc.CallOption) (*DeleteAllHistoryResponse, error)
	GetHistorysFiltered(ctx context.Context, in *GetHistorysFilteredRequest, opts ...grpc.CallOption) (*GetHistorysFilteredResponse, error)
}

type dbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDbServiceClient(cc grpc.ClientConnInterface) DbServiceClient {
	return &dbServiceClient{cc}
}

func (c *dbServiceClient) GetDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailResponse)
	err := c.cc.Invoke(ctx, DbService_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) UpsertDetail(ctx context.Context, in *UpsertDetailRequest, opts ...grpc.CallOption) (*UpsertDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertDetailResponse)
	err := c.cc.Invoke(ctx, DbService_UpsertDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetAllFavorite(ctx context.Context, in *GetAllFavoriteRequest, opts ...grpc.CallOption) (*GetAllFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllFavoriteResponse)
	err := c.cc.Invoke(ctx, DbService_GetAllFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetFavoriteByPackageAndUrl(ctx context.Context, in *GetFavoriteByPackageAndUrlRequest, opts ...grpc.CallOption) (*GetFavoriteByPackageAndUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteByPackageAndUrlResponse)
	err := c.cc.Invoke(ctx, DbService_GetFavoriteByPackageAndUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) PutFavoriteByIndex(ctx context.Context, in *PutFavoriteByIndexRequest, opts ...grpc.CallOption) (*PutFavoriteByIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutFavoriteByIndexResponse)
	err := c.cc.Invoke(ctx, DbService_PutFavoriteByIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) PutFavorite(ctx context.Context, in *PutFavoriteRequest, opts ...grpc.CallOption) (*PutFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutFavoriteResponse)
	err := c.cc.Invoke(ctx, DbService_PutFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteFavorite(ctx context.Context, in *DeleteFavoriteRequest, opts ...grpc.CallOption) (*DeleteFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavoriteResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetFavoriteGroupsById(ctx context.Context, in *GetFavoriteGroupsByIdRequest, opts ...grpc.CallOption) (*GetFavoriteGroupsByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteGroupsByIdResponse)
	err := c.cc.Invoke(ctx, DbService_GetFavoriteGroupsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetAllFavoriteGroup(ctx context.Context, in *GetAllFavoriteGroupRequest, opts ...grpc.CallOption) (*GetAllFavoriteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllFavoriteGroupResponse)
	err := c.cc.Invoke(ctx, DbService_GetAllFavoriteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) PutFavoriteGroup(ctx context.Context, in *PutFavoriteGroupRequest, opts ...grpc.CallOption) (*PutFavoriteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutFavoriteGroupResponse)
	err := c.cc.Invoke(ctx, DbService_PutFavoriteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) RenameFavoriteGroup(ctx context.Context, in *RenameFavoriteGroupRequest, opts ...grpc.CallOption) (*RenameFavoriteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFavoriteGroupResponse)
	err := c.cc.Invoke(ctx, DbService_RenameFavoriteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteFavoriteGroup(ctx context.Context, in *DeleteFavoriteGroupRequest, opts ...grpc.CallOption) (*DeleteFavoriteGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavoriteGroupResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteFavoriteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetFavoriteGroupsByFavorite(ctx context.Context, in *GetFavoriteGroupsByFavoriteRequest, opts ...grpc.CallOption) (*GetFavoriteGroupsByFavoriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteGroupsByFavoriteResponse)
	err := c.cc.Invoke(ctx, DbService_GetFavoriteGroupsByFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetHistoriesByType(ctx context.Context, in *GetHistoriesByTypeRequest, opts ...grpc.CallOption) (*GetHistoriesByTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoriesByTypeResponse)
	err := c.cc.Invoke(ctx, DbService_GetHistoriesByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetHistoryByPackageAndDetailUrl(ctx context.Context, in *GetHistoryByPackageAndDetailUrlRequest, opts ...grpc.CallOption) (*GetHistoryByPackageAndDetailUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryByPackageAndDetailUrlResponse)
	err := c.cc.Invoke(ctx, DbService_GetHistoryByPackageAndDetailUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) PutHistory(ctx context.Context, in *PutHistoryRequest, opts ...grpc.CallOption) (*PutHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutHistoryResponse)
	err := c.cc.Invoke(ctx, DbService_PutHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteHistoryByPackageAndUrl(ctx context.Context, in *DeleteHistoryByPackageAndUrlRequest, opts ...grpc.CallOption) (*DeleteHistoryByPackageAndUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHistoryByPackageAndUrlResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteHistoryByPackageAndUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) DeleteAllHistory(ctx context.Context, in *DeleteAllHistoryRequest, opts ...grpc.CallOption) (*DeleteAllHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAllHistoryResponse)
	err := c.cc.Invoke(ctx, DbService_DeleteAllHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetHistorysFiltered(ctx context.Context, in *GetHistorysFilteredRequest, opts ...grpc.CallOption) (*GetHistorysFilteredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistorysFilteredResponse)
	err := c.cc.Invoke(ctx, DbService_GetHistorysFiltered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServiceServer is the server API for DbService service.
// All implementations must embed UnimplementedDbServiceServer
// for forward compatibility.
type DbServiceServer interface {
	// Detail
	GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error)
	UpsertDetail(context.Context, *UpsertDetailRequest) (*UpsertDetailResponse, error)
	// Favorite
	GetAllFavorite(context.Context, *GetAllFavoriteRequest) (*GetAllFavoriteResponse, error)
	GetFavoriteByPackageAndUrl(context.Context, *GetFavoriteByPackageAndUrlRequest) (*GetFavoriteByPackageAndUrlResponse, error)
	PutFavoriteByIndex(context.Context, *PutFavoriteByIndexRequest) (*PutFavoriteByIndexResponse, error)
	PutFavorite(context.Context, *PutFavoriteRequest) (*PutFavoriteResponse, error)
	DeleteFavorite(context.Context, *DeleteFavoriteRequest) (*DeleteFavoriteResponse, error)
	// Favorite Group
	GetFavoriteGroupsById(context.Context, *GetFavoriteGroupsByIdRequest) (*GetFavoriteGroupsByIdResponse, error)
	GetAllFavoriteGroup(context.Context, *GetAllFavoriteGroupRequest) (*GetAllFavoriteGroupResponse, error)
	PutFavoriteGroup(context.Context, *PutFavoriteGroupRequest) (*PutFavoriteGroupResponse, error)
	RenameFavoriteGroup(context.Context, *RenameFavoriteGroupRequest) (*RenameFavoriteGroupResponse, error)
	DeleteFavoriteGroup(context.Context, *DeleteFavoriteGroupRequest) (*DeleteFavoriteGroupResponse, error)
	GetFavoriteGroupsByFavorite(context.Context, *GetFavoriteGroupsByFavoriteRequest) (*GetFavoriteGroupsByFavoriteResponse, error)
	// History
	GetHistoriesByType(context.Context, *GetHistoriesByTypeRequest) (*GetHistoriesByTypeResponse, error)
	GetHistoryByPackageAndDetailUrl(context.Context, *GetHistoryByPackageAndDetailUrlRequest) (*GetHistoryByPackageAndDetailUrlResponse, error)
	PutHistory(context.Context, *PutHistoryRequest) (*PutHistoryResponse, error)
	DeleteHistoryByPackageAndUrl(context.Context, *DeleteHistoryByPackageAndUrlRequest) (*DeleteHistoryByPackageAndUrlResponse, error)
	DeleteAllHistory(context.Context, *DeleteAllHistoryRequest) (*DeleteAllHistoryResponse, error)
	GetHistorysFiltered(context.Context, *GetHistorysFilteredRequest) (*GetHistorysFilteredResponse, error)
	mustEmbedUnimplementedDbServiceServer()
}

// UnimplementedDbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbServiceServer struct{}

func (UnimplementedDbServiceServer) GetDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedDbServiceServer) UpsertDetail(context.Context, *UpsertDetailRequest) (*UpsertDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertDetail not implemented")
}
func (UnimplementedDbServiceServer) GetAllFavorite(context.Context, *GetAllFavoriteRequest) (*GetAllFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllFavorite not implemented")
}
func (UnimplementedDbServiceServer) GetFavoriteByPackageAndUrl(context.Context, *GetFavoriteByPackageAndUrlRequest) (*GetFavoriteByPackageAndUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoriteByPackageAndUrl not implemented")
}
func (UnimplementedDbServiceServer) PutFavoriteByIndex(context.Context, *PutFavoriteByIndexRequest) (*PutFavoriteByIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutFavoriteByIndex not implemented")
}
func (UnimplementedDbServiceServer) PutFavorite(context.Context, *PutFavoriteRequest) (*PutFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutFavorite not implemented")
}
func (UnimplementedDbServiceServer) DeleteFavorite(context.Context, *DeleteFavoriteRequest) (*DeleteFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFavorite not implemented")
}
func (UnimplementedDbServiceServer) GetFavoriteGroupsById(context.Context, *GetFavoriteGroupsByIdRequest) (*GetFavoriteGroupsByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoriteGroupsById not implemented")
}
func (UnimplementedDbServiceServer) GetAllFavoriteGroup(context.Context, *GetAllFavoriteGroupRequest) (*GetAllFavoriteGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllFavoriteGroup not implemented")
}
func (UnimplementedDbServiceServer) PutFavoriteGroup(context.Context, *PutFavoriteGroupRequest) (*PutFavoriteGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutFavoriteGroup not implemented")
}
func (UnimplementedDbServiceServer) RenameFavoriteGroup(context.Context, *RenameFavoriteGroupRequest) (*RenameFavoriteGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFavoriteGroup not implemented")
}
func (UnimplementedDbServiceServer) DeleteFavoriteGroup(context.Context, *DeleteFavoriteGroupRequest) (*DeleteFavoriteGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFavoriteGroup not implemented")
}
func (UnimplementedDbServiceServer) GetFavoriteGroupsByFavorite(context.Context, *GetFavoriteGroupsByFavoriteRequest) (*GetFavoriteGroupsByFavoriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoriteGroupsByFavorite not implemented")
}
func (UnimplementedDbServiceServer) GetHistoriesByType(context.Context, *GetHistoriesByTypeRequest) (*GetHistoriesByTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoriesByType not implemented")
}
func (UnimplementedDbServiceServer) GetHistoryByPackageAndDetailUrl(context.Context, *GetHistoryByPackageAndDetailUrlRequest) (*GetHistoryByPackageAndDetailUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryByPackageAndDetailUrl not implemented")
}
func (UnimplementedDbServiceServer) PutHistory(context.Context, *PutHistoryRequest) (*PutHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutHistory not implemented")
}
func (UnimplementedDbServiceServer) DeleteHistoryByPackageAndUrl(context.Context, *DeleteHistoryByPackageAndUrlRequest) (*DeleteHistoryByPackageAndUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHistoryByPackageAndUrl not implemented")
}
func (UnimplementedDbServiceServer) DeleteAllHistory(context.Context, *DeleteAllHistoryRequest) (*DeleteAllHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAllHistory not implemented")
}
func (UnimplementedDbServiceServer) GetHistorysFiltered(context.Context, *GetHistorysFilteredRequest) (*GetHistorysFilteredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistorysFiltered not implemented")
}
func (UnimplementedDbServiceServer) mustEmbedUnimplementedDbServiceServer() {}
func (UnimplementedDbServiceServer) testEmbeddedByValue()                   {}

// UnsafeDbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbServiceServer will
// result in compilation errors.
type UnsafeDbServiceServer interface {
	mustEmbedUnimplementedDbServiceServer()
}

func RegisterDbServiceServer(s grpc.ServiceRegistrar, srv DbServiceServer) {
	// If the following call panics, it indicates UnimplementedDbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DbService_ServiceDesc, srv)
}

func _DbService_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetDetail(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_UpsertDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).UpsertDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_UpsertDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).UpsertDetail(ctx, req.(*UpsertDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetAllFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetAllFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetAllFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetAllFavorite(ctx, req.(*GetAllFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetFavoriteByPackageAndUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteByPackageAndUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetFavoriteByPackageAndUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetFavoriteByPackageAndUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetFavoriteByPackageAndUrl(ctx, req.(*GetFavoriteByPackageAndUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_PutFavoriteByIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFavoriteByIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).PutFavoriteByIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_PutFavoriteByIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).PutFavoriteByIndex(ctx, req.(*PutFavoriteByIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_PutFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).PutFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_PutFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).PutFavorite(ctx, req.(*PutFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteFavorite(ctx, req.(*DeleteFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetFavoriteGroupsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteGroupsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetFavoriteGroupsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetFavoriteGroupsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetFavoriteGroupsById(ctx, req.(*GetFavoriteGroupsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetAllFavoriteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFavoriteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetAllFavoriteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetAllFavoriteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetAllFavoriteGroup(ctx, req.(*GetAllFavoriteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_PutFavoriteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutFavoriteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).PutFavoriteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_PutFavoriteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).PutFavoriteGroup(ctx, req.(*PutFavoriteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_RenameFavoriteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFavoriteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).RenameFavoriteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_RenameFavoriteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).RenameFavoriteGroup(ctx, req.(*RenameFavoriteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteFavoriteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavoriteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteFavoriteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteFavoriteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteFavoriteGroup(ctx, req.(*DeleteFavoriteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetFavoriteGroupsByFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteGroupsByFavoriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetFavoriteGroupsByFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetFavoriteGroupsByFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetFavoriteGroupsByFavorite(ctx, req.(*GetFavoriteGroupsByFavoriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetHistoriesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoriesByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetHistoriesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetHistoriesByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetHistoriesByType(ctx, req.(*GetHistoriesByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetHistoryByPackageAndDetailUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryByPackageAndDetailUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetHistoryByPackageAndDetailUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetHistoryByPackageAndDetailUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetHistoryByPackageAndDetailUrl(ctx, req.(*GetHistoryByPackageAndDetailUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_PutHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).PutHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_PutHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).PutHistory(ctx, req.(*PutHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteHistoryByPackageAndUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHistoryByPackageAndUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteHistoryByPackageAndUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteHistoryByPackageAndUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteHistoryByPackageAndUrl(ctx, req.(*DeleteHistoryByPackageAndUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_DeleteAllHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).DeleteAllHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_DeleteAllHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).DeleteAllHistory(ctx, req.(*DeleteAllHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetHistorysFiltered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistorysFilteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetHistorysFiltered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DbService_GetHistorysFiltered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetHistorysFiltered(ctx, req.(*GetHistorysFilteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DbService_ServiceDesc is the grpc.ServiceDesc for DbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "miru.DbService",
	HandlerType: (*DbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDetail",
			Handler:    _DbService_GetDetail_Handler,
		},
		{
			MethodName: "UpsertDetail",
			Handler:    _DbService_UpsertDetail_Handler,
		},
		{
			MethodName: "GetAllFavorite",
			Handler:    _DbService_GetAllFavorite_Handler,
		},
		{
			MethodName: "GetFavoriteByPackageAndUrl",
			Handler:    _DbService_GetFavoriteByPackageAndUrl_Handler,
		},
		{
			MethodName: "PutFavoriteByIndex",
			Handler:    _DbService_PutFavoriteByIndex_Handler,
		},
		{
			MethodName: "PutFavorite",
			Handler:    _DbService_PutFavorite_Handler,
		},
		{
			MethodName: "DeleteFavorite",
			Handler:    _DbService_DeleteFavorite_Handler,
		},
		{
			MethodName: "GetFavoriteGroupsById",
			Handler:    _DbService_GetFavoriteGroupsById_Handler,
		},
		{
			MethodName: "GetAllFavoriteGroup",
			Handler:    _DbService_GetAllFavoriteGroup_Handler,
		},
		{
			MethodName: "PutFavoriteGroup",
			Handler:    _DbService_PutFavoriteGroup_Handler,
		},
		{
			MethodName: "RenameFavoriteGroup",
			Handler:    _DbService_RenameFavoriteGroup_Handler,
		},
		{
			MethodName: "DeleteFavoriteGroup",
			Handler:    _DbService_DeleteFavoriteGroup_Handler,
		},
		{
			MethodName: "GetFavoriteGroupsByFavorite",
			Handler:    _DbService_GetFavoriteGroupsByFavorite_Handler,
		},
		{
			MethodName: "GetHistoriesByType",
			Handler:    _DbService_GetHistoriesByType_Handler,
		},
		{
			MethodName: "GetHistoryByPackageAndDetailUrl",
			Handler:    _DbService_GetHistoryByPackageAndDetailUrl_Handler,
		},
		{
			MethodName: "PutHistory",
			Handler:    _DbService_PutHistory_Handler,
		},
		{
			MethodName: "DeleteHistoryByPackageAndUrl",
			Handler:    _DbService_DeleteHistoryByPackageAndUrl_Handler,
		},
		{
			MethodName: "DeleteAllHistory",
			Handler:    _DbService_DeleteAllHistory_Handler,
		},
		{
			MethodName: "GetHistorysFiltered",
			Handler:    _DbService_GetHistorysFiltered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/db.proto",
}
