// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/extension_model.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionSettingType int32

const (
	ExtensionSettingType_input  ExtensionSettingType = 0
	ExtensionSettingType_radio  ExtensionSettingType = 1
	ExtensionSettingType_toggle ExtensionSettingType = 2
)

// Enum value maps for ExtensionSettingType.
var (
	ExtensionSettingType_name = map[int32]string{
		0: "input",
		1: "radio",
		2: "toggle",
	}
	ExtensionSettingType_value = map[string]int32{
		"input":  0,
		"radio":  1,
		"toggle": 2,
	}
)

func (x ExtensionSettingType) Enum() *ExtensionSettingType {
	p := new(ExtensionSettingType)
	*p = x
	return p
}

func (x ExtensionSettingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionSettingType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_extension_model_proto_enumTypes[0].Descriptor()
}

func (ExtensionSettingType) Type() protoreflect.EnumType {
	return &file_proto_extension_model_proto_enumTypes[0]
}

func (x ExtensionSettingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionSettingType.Descriptor instead.
func (ExtensionSettingType) EnumDescriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{0}
}

type ExtensionListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Update        string                 `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionListItem) Reset() {
	*x = ExtensionListItem{}
	mi := &file_proto_extension_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionListItem) ProtoMessage() {}

func (x *ExtensionListItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionListItem.ProtoReflect.Descriptor instead.
func (*ExtensionListItem) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{0}
}

func (x *ExtensionListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionListItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtensionListItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ExtensionListItem) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *ExtensionListItem) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// FilterOption pairs a stable option key with a display label.
type FilterOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOption) Reset() {
	*x = FilterOption{}
	mi := &file_proto_extension_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOption) ProtoMessage() {}

func (x *FilterOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOption.ProtoReflect.Descriptor instead.
func (*FilterOption) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{1}
}

func (x *FilterOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// SelectFilter is a single-value filter: the user picks exactly one option
// (max == 1). Default is the key of the pre-selected option.
type SelectFilter struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Title         string                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Default       string                   `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Options       map[string]*FilterOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectFilter) Reset() {
	*x = SelectFilter{}
	mi := &file_proto_extension_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectFilter) ProtoMessage() {}

func (x *SelectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectFilter.ProtoReflect.Descriptor instead.
func (*SelectFilter) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{2}
}

func (x *SelectFilter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SelectFilter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *SelectFilter) GetOptions() map[string]*FilterOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// MultiSelectFilter is a multi-value filter: the user picks between min and
// max options. Default is the list of pre-selected option keys.
type MultiSelectFilter struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Title         string                   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Min           int32                    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Default       []string                 `protobuf:"bytes,4,rep,name=default,proto3" json:"default,omitempty"`
	Options       map[string]*FilterOption `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSelectFilter) Reset() {
	*x = MultiSelectFilter{}
	mi := &file_proto_extension_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSelectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSelectFilter) ProtoMessage() {}

func (x *MultiSelectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSelectFilter.ProtoReflect.Descriptor instead.
func (*MultiSelectFilter) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{3}
}

func (x *MultiSelectFilter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MultiSelectFilter) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MultiSelectFilter) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *MultiSelectFilter) GetDefault() []string {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *MultiSelectFilter) GetOptions() map[string]*FilterOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// RangeFilter is a numeric range filter with inclusive min/max bounds and
// separate default values. No options map; the UI typically renders a
// slider or two number inputs.
type RangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Min           int32                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	DefaultMin    int32                  `protobuf:"varint,4,opt,name=default_min,json=defaultMin,proto3" json:"default_min,omitempty"`
	DefaultMax    int32                  `protobuf:"varint,5,opt,name=default_max,json=defaultMax,proto3" json:"default_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeFilter) Reset() {
	*x = RangeFilter{}
	mi := &file_proto_extension_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeFilter) ProtoMessage() {}

func (x *RangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeFilter.ProtoReflect.Descriptor instead.
func (*RangeFilter) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{4}
}

func (x *RangeFilter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RangeFilter) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *RangeFilter) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *RangeFilter) GetDefaultMin() int32 {
	if x != nil {
		return x.DefaultMin
	}
	return 0
}

func (x *RangeFilter) GetDefaultMax() int32 {
	if x != nil {
		return x.DefaultMax
	}
	return 0
}

// ExtensionFilter is the typed filter definition returned by CreateFilter.
// Exactly one of its variants is set; consumers switch on the oneof.
type ExtensionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ExtensionFilter_Select
	//	*ExtensionFilter_MultiSelect
	//	*ExtensionFilter_Range
	Kind          isExtensionFilter_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionFilter) Reset() {
	*x = ExtensionFilter{}
	mi := &file_proto_extension_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionFilter) ProtoMessage() {}

func (x *ExtensionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionFilter.ProtoReflect.Descriptor instead.
func (*ExtensionFilter) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{5}
}

func (x *ExtensionFilter) GetKind() isExtensionFilter_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ExtensionFilter) GetSelect() *SelectFilter {
	if x != nil {
		if x, ok := x.Kind.(*ExtensionFilter_Select); ok {
			return x.Select
		}
	}
	return nil
}

func (x *ExtensionFilter) GetMultiSelect() *MultiSelectFilter {
	if x != nil {
		if x, ok := x.Kind.(*ExtensionFilter_MultiSelect); ok {
			return x.MultiSelect
		}
	}
	return nil
}

func (x *ExtensionFilter) GetRange() *RangeFilter {
	if x != nil {
		if x, ok := x.Kind.(*ExtensionFilter_Range); ok {
			return x.Range
		}
	}
	return nil
}

type isExtensionFilter_Kind interface {
	isExtensionFilter_Kind()
}

type ExtensionFilter_Select struct {
	Select *SelectFilter `protobuf:"bytes,1,opt,name=select,proto3,oneof"`
}

type ExtensionFilter_MultiSelect struct {
	MultiSelect *MultiSelectFilter `protobuf:"bytes,2,opt,name=multi_select,json=multiSelect,proto3,oneof"`
}

type ExtensionFilter_Range struct {
	Range *RangeFilter `protobuf:"bytes,3,opt,name=range,proto3,oneof"`
}

func (*ExtensionFilter_Select) isExtensionFilter_Kind() {}

func (*ExtensionFilter_MultiSelect) isExtensionFilter_Kind() {}

func (*ExtensionFilter_Range) isExtensionFilter_Kind() {}

type ExtensionDetail struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Title         *string                  `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Cover         *string                  `protobuf:"bytes,2,opt,name=cover,proto3,oneof" json:"cover,omitempty"`
	Desc          *string                  `protobuf:"bytes,3,opt,name=desc,proto3,oneof" json:"desc,omitempty"`
	Episodes      []*ExtensionEpisodeGroup `protobuf:"bytes,4,rep,name=episodes,proto3" json:"episodes,omitempty"`
	Headers       map[string]string        `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionDetail) Reset() {
	*x = ExtensionDetail{}
	mi := &file_proto_extension_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionDetail) ProtoMessage() {}

func (x *ExtensionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionDetail.ProtoReflect.Descriptor instead.
func (*ExtensionDetail) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{6}
}

func (x *ExtensionDetail) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ExtensionDetail) GetCover() string {
	if x != nil && x.Cover != nil {
		return *x.Cover
	}
	return ""
}

func (x *ExtensionDetail) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

func (x *ExtensionDetail) GetEpisodes() []*ExtensionEpisodeGroup {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *ExtensionDetail) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ExtensionEpisodeGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Urls          []*ExtensionEpisode    `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionEpisodeGroup) Reset() {
	*x = ExtensionEpisodeGroup{}
	mi := &file_proto_extension_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionEpisodeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionEpisodeGroup) ProtoMessage() {}

func (x *ExtensionEpisodeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionEpisodeGroup.ProtoReflect.Descriptor instead.
func (*ExtensionEpisodeGroup) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{7}
}

func (x *ExtensionEpisodeGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionEpisodeGroup) GetUrls() []*ExtensionEpisode {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ExtensionEpisode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Update        string                 `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionEpisode) Reset() {
	*x = ExtensionEpisode{}
	mi := &file_proto_extension_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionEpisode) ProtoMessage() {}

func (x *ExtensionEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionEpisode.ProtoReflect.Descriptor instead.
func (*ExtensionEpisode) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{8}
}

func (x *ExtensionEpisode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionEpisode) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtensionEpisode) GetUpdate() string {
	if x != nil {
		return x.Update
	}
	return ""
}

func (x *ExtensionEpisode) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type ExtensionMirror struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url   string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Headers the client must send when fetching the mirror stream (e.g.
	// Referer/User-Agent required by the source CDN). Populated by the golang
	// (V2) runtime from the resolved stream's referer and the browser UA.
	Headers       map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionMirror) Reset() {
	*x = ExtensionMirror{}
	mi := &file_proto_extension_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionMirror) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMirror) ProtoMessage() {}

func (x *ExtensionMirror) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMirror.ProtoReflect.Descriptor instead.
func (*ExtensionMirror) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{9}
}

func (x *ExtensionMirror) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionMirror) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtensionMirror) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ExtensionMirrorGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Mirrors       []*ExtensionMirror     `protobuf:"bytes,2,rep,name=mirrors,proto3" json:"mirrors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionMirrorGroup) Reset() {
	*x = ExtensionMirrorGroup{}
	mi := &file_proto_extension_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionMirrorGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMirrorGroup) ProtoMessage() {}

func (x *ExtensionMirrorGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMirrorGroup.ProtoReflect.Descriptor instead.
func (*ExtensionMirrorGroup) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{10}
}

func (x *ExtensionMirrorGroup) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionMirrorGroup) GetMirrors() []*ExtensionMirror {
	if x != nil {
		return x.Mirrors
	}
	return nil
}

type ExtensionBangumiWatchSubtitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      *string                `protobuf:"bytes,1,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionBangumiWatchSubtitle) Reset() {
	*x = ExtensionBangumiWatchSubtitle{}
	mi := &file_proto_extension_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionBangumiWatchSubtitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionBangumiWatchSubtitle) ProtoMessage() {}

func (x *ExtensionBangumiWatchSubtitle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionBangumiWatchSubtitle.ProtoReflect.Descriptor instead.
func (*ExtensionBangumiWatchSubtitle) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{11}
}

func (x *ExtensionBangumiWatchSubtitle) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *ExtensionBangumiWatchSubtitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionBangumiWatchSubtitle) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Torrent resolution is handled on the frontend, not by the extension. These
// messages describe the resolved torrent's metainfo and file tree so the
// frontend can read the tree and decide which files to download.
type ExtensionBangumiWatchTorrentFileTreeFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	PiecesRoot    string                 `protobuf:"bytes,2,opt,name=piecesRoot,proto3" json:"piecesRoot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionBangumiWatchTorrentFileTreeFile) Reset() {
	*x = ExtensionBangumiWatchTorrentFileTreeFile{}
	mi := &file_proto_extension_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionBangumiWatchTorrentFileTreeFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionBangumiWatchTorrentFileTreeFile) ProtoMessage() {}

func (x *ExtensionBangumiWatchTorrentFileTreeFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionBangumiWatchTorrentFileTreeFile.ProtoReflect.Descriptor instead.
func (*ExtensionBangumiWatchTorrentFileTreeFile) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{12}
}

func (x *ExtensionBangumiWatchTorrentFileTreeFile) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ExtensionBangumiWatchTorrentFileTreeFile) GetPiecesRoot() string {
	if x != nil {
		return x.PiecesRoot
	}
	return ""
}

type ExtensionBangumiWatchTorrentFileTree struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	File          *ExtensionBangumiWatchTorrentFileTreeFile        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Dir           map[string]*ExtensionBangumiWatchTorrentFileTree `protobuf:"bytes,2,rep,name=dir,proto3" json:"dir,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionBangumiWatchTorrentFileTree) Reset() {
	*x = ExtensionBangumiWatchTorrentFileTree{}
	mi := &file_proto_extension_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionBangumiWatchTorrentFileTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionBangumiWatchTorrentFileTree) ProtoMessage() {}

func (x *ExtensionBangumiWatchTorrentFileTree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionBangumiWatchTorrentFileTree.ProtoReflect.Descriptor instead.
func (*ExtensionBangumiWatchTorrentFileTree) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{13}
}

func (x *ExtensionBangumiWatchTorrentFileTree) GetFile() *ExtensionBangumiWatchTorrentFileTreeFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ExtensionBangumiWatchTorrentFileTree) GetDir() map[string]*ExtensionBangumiWatchTorrentFileTree {
	if x != nil {
		return x.Dir
	}
	return nil
}

type ExtensionBangumiWatchTorrentDetail struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	PieceLength   *int32                                `protobuf:"varint,1,opt,name=pieceLength,proto3,oneof" json:"pieceLength,omitempty"`
	Pieces        *string                               `protobuf:"bytes,2,opt,name=pieces,proto3,oneof" json:"pieces,omitempty"`
	Name          *string                               `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	NameUtf8      *string                               `protobuf:"bytes,4,opt,name=nameUtf8,proto3,oneof" json:"nameUtf8,omitempty"`
	Length        *int64                                `protobuf:"varint,5,opt,name=length,proto3,oneof" json:"length,omitempty"`
	Source        *string                               `protobuf:"bytes,6,opt,name=source,proto3,oneof" json:"source,omitempty"`
	MetaVersion   *int32                                `protobuf:"varint,7,opt,name=metaVersion,proto3,oneof" json:"metaVersion,omitempty"`
	FileTree      *ExtensionBangumiWatchTorrentFileTree `protobuf:"bytes,8,opt,name=fileTree,proto3" json:"fileTree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionBangumiWatchTorrentDetail) Reset() {
	*x = ExtensionBangumiWatchTorrentDetail{}
	mi := &file_proto_extension_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionBangumiWatchTorrentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionBangumiWatchTorrentDetail) ProtoMessage() {}

func (x *ExtensionBangumiWatchTorrentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionBangumiWatchTorrentDetail.ProtoReflect.Descriptor instead.
func (*ExtensionBangumiWatchTorrentDetail) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{14}
}

func (x *ExtensionBangumiWatchTorrentDetail) GetPieceLength() int32 {
	if x != nil && x.PieceLength != nil {
		return *x.PieceLength
	}
	return 0
}

func (x *ExtensionBangumiWatchTorrentDetail) GetPieces() string {
	if x != nil && x.Pieces != nil {
		return *x.Pieces
	}
	return ""
}

func (x *ExtensionBangumiWatchTorrentDetail) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ExtensionBangumiWatchTorrentDetail) GetNameUtf8() string {
	if x != nil && x.NameUtf8 != nil {
		return *x.NameUtf8
	}
	return ""
}

func (x *ExtensionBangumiWatchTorrentDetail) GetLength() int64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ExtensionBangumiWatchTorrentDetail) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ExtensionBangumiWatchTorrentDetail) GetMetaVersion() int32 {
	if x != nil && x.MetaVersion != nil {
		return *x.MetaVersion
	}
	return 0
}

func (x *ExtensionBangumiWatchTorrentDetail) GetFileTree() *ExtensionBangumiWatchTorrentFileTree {
	if x != nil {
		return x.FileTree
	}
	return nil
}

type ExtensionBangumiWatchTorrent struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	InfoHash      string                              `protobuf:"bytes,1,opt,name=infoHash,proto3" json:"infoHash,omitempty"`
	Detail        *ExtensionBangumiWatchTorrentDetail `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Files         []string                            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionBangumiWatchTorrent) Reset() {
	*x = ExtensionBangumiWatchTorrent{}
	mi := &file_proto_extension_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionBangumiWatchTorrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionBangumiWatchTorrent) ProtoMessage() {}

func (x *ExtensionBangumiWatchTorrent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionBangumiWatchTorrent.ProtoReflect.Descriptor instead.
func (*ExtensionBangumiWatchTorrent) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{15}
}

func (x *ExtensionBangumiWatchTorrent) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *ExtensionBangumiWatchTorrent) GetDetail() *ExtensionBangumiWatchTorrentDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *ExtensionBangumiWatchTorrent) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type ExtensionBangumiWatch struct {
	state      protoimpl.MessageState           `protogen:"open.v1"`
	Type       string                           `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url        string                           `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Subtitles  []*ExtensionBangumiWatchSubtitle `protobuf:"bytes,3,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	Headers    map[string]string                `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AudioTrack *string                          `protobuf:"bytes,5,opt,name=audioTrack,proto3,oneof" json:"audioTrack,omitempty"`
	// Resolved torrent handle. Populated when the extension's Watch returns a
	// magnet:/torrent URL (or resolves one explicitly); the frontend reads it to
	// render the file tree and pick files to download. Absent for plain streams.
	Torrent       *ExtensionBangumiWatchTorrent `protobuf:"bytes,6,opt,name=torrent,proto3" json:"torrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionBangumiWatch) Reset() {
	*x = ExtensionBangumiWatch{}
	mi := &file_proto_extension_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionBangumiWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionBangumiWatch) ProtoMessage() {}

func (x *ExtensionBangumiWatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionBangumiWatch.ProtoReflect.Descriptor instead.
func (*ExtensionBangumiWatch) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{16}
}

func (x *ExtensionBangumiWatch) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExtensionBangumiWatch) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtensionBangumiWatch) GetSubtitles() []*ExtensionBangumiWatchSubtitle {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

func (x *ExtensionBangumiWatch) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ExtensionBangumiWatch) GetAudioTrack() string {
	if x != nil && x.AudioTrack != nil {
		return *x.AudioTrack
	}
	return ""
}

func (x *ExtensionBangumiWatch) GetTorrent() *ExtensionBangumiWatchTorrent {
	if x != nil {
		return x.Torrent
	}
	return nil
}

type ExtensionMangaWatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionMangaWatch) Reset() {
	*x = ExtensionMangaWatch{}
	mi := &file_proto_extension_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionMangaWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionMangaWatch) ProtoMessage() {}

func (x *ExtensionMangaWatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionMangaWatch.ProtoReflect.Descriptor instead.
func (*ExtensionMangaWatch) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{17}
}

func (x *ExtensionMangaWatch) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ExtensionMangaWatch) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ExtensionFikushonWatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []string               `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      *string                `protobuf:"bytes,3,opt,name=subtitle,proto3,oneof" json:"subtitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionFikushonWatch) Reset() {
	*x = ExtensionFikushonWatch{}
	mi := &file_proto_extension_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionFikushonWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionFikushonWatch) ProtoMessage() {}

func (x *ExtensionFikushonWatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionFikushonWatch.ProtoReflect.Descriptor instead.
func (*ExtensionFikushonWatch) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{18}
}

func (x *ExtensionFikushonWatch) GetContent() []string {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExtensionFikushonWatch) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionFikushonWatch) GetSubtitle() string {
	if x != nil && x.Subtitle != nil {
		return *x.Subtitle
	}
	return ""
}

// ExtensionAllWatch bundles the three per-type watch shapes (manga, fikushon and
// bangumi) behind a single "all" extension type. An extension that declares
// @type all returns this message so the client can render any of the three
// media kinds from one watch call.
type ExtensionAllWatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Manga         *ExtensionMangaWatch    `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	Fikushon      *ExtensionFikushonWatch `protobuf:"bytes,2,opt,name=fikushon,proto3" json:"fikushon,omitempty"`
	Bangumi       *ExtensionBangumiWatch  `protobuf:"bytes,3,opt,name=bangumi,proto3" json:"bangumi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionAllWatch) Reset() {
	*x = ExtensionAllWatch{}
	mi := &file_proto_extension_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionAllWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionAllWatch) ProtoMessage() {}

func (x *ExtensionAllWatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionAllWatch.ProtoReflect.Descriptor instead.
func (*ExtensionAllWatch) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{19}
}

func (x *ExtensionAllWatch) GetManga() *ExtensionMangaWatch {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *ExtensionAllWatch) GetFikushon() *ExtensionFikushonWatch {
	if x != nil {
		return x.Fikushon
	}
	return nil
}

func (x *ExtensionAllWatch) GetBangumi() *ExtensionBangumiWatch {
	if x != nil {
		return x.Bangumi
	}
	return nil
}

// V2
type ExtensionWatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Groups        []*ExtensionMirrorGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	DefaultGroup  *string                 `protobuf:"bytes,2,opt,name=default_group,json=defaultGroup,proto3,oneof" json:"default_group,omitempty"`
	DefaultIndex  *int32                  `protobuf:"varint,3,opt,name=default_index,json=defaultIndex,proto3,oneof" json:"default_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionWatch) Reset() {
	*x = ExtensionWatch{}
	mi := &file_proto_extension_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionWatch) ProtoMessage() {}

func (x *ExtensionWatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionWatch.ProtoReflect.Descriptor instead.
func (*ExtensionWatch) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{20}
}

func (x *ExtensionWatch) GetGroups() []*ExtensionMirrorGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ExtensionWatch) GetDefaultGroup() string {
	if x != nil && x.DefaultGroup != nil {
		return *x.DefaultGroup
	}
	return ""
}

func (x *ExtensionWatch) GetDefaultIndex() int32 {
	if x != nil && x.DefaultIndex != nil {
		return *x.DefaultIndex
	}
	return 0
}

type GithubExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	License       string                 `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Icon          *string                `protobuf:"bytes,6,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Lang          string                 `protobuf:"bytes,8,opt,name=lang,proto3" json:"lang,omitempty"`
	WebSite       string                 `protobuf:"bytes,9,opt,name=webSite,proto3" json:"webSite,omitempty"`
	Nsfw          bool                   `protobuf:"varint,10,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Package       string                 `protobuf:"bytes,11,opt,name=package,proto3" json:"package,omitempty"`
	Tags          []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GithubExtension) Reset() {
	*x = GithubExtension{}
	mi := &file_proto_extension_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GithubExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubExtension) ProtoMessage() {}

func (x *GithubExtension) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubExtension.ProtoReflect.Descriptor instead.
func (*GithubExtension) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{21}
}

func (x *GithubExtension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GithubExtension) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *GithubExtension) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *GithubExtension) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GithubExtension) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GithubExtension) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *GithubExtension) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GithubExtension) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *GithubExtension) GetWebSite() string {
	if x != nil {
		return x.WebSite
	}
	return ""
}

func (x *GithubExtension) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *GithubExtension) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *GithubExtension) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ExtensionRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extensions    []*GithubExtension     `protobuf:"bytes,1,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionRepo) Reset() {
	*x = ExtensionRepo{}
	mi := &file_proto_extension_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionRepo) ProtoMessage() {}

func (x *ExtensionRepo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionRepo.ProtoReflect.Descriptor instead.
func (*ExtensionRepo) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{22}
}

func (x *ExtensionRepo) GetExtensions() []*GithubExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *ExtensionRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExtensionRepo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RepoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoConfig) Reset() {
	*x = RepoConfig{}
	mi := &file_proto_extension_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoConfig) ProtoMessage() {}

func (x *RepoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoConfig.ProtoReflect.Descriptor instead.
func (*RepoConfig) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{23}
}

func (x *RepoConfig) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RepoConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepoConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ExtensionSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Package       string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,5,opt,name=value,proto3,oneof" json:"value,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,6,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	Type          ExtensionSettingType   `protobuf:"varint,7,opt,name=type,proto3,enum=miru.ExtensionSettingType" json:"type,omitempty"`
	Description   *string                `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Options       *string                `protobuf:"bytes,9,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionSetting) Reset() {
	*x = ExtensionSetting{}
	mi := &file_proto_extension_model_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionSetting) ProtoMessage() {}

func (x *ExtensionSetting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_extension_model_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionSetting.ProtoReflect.Descriptor instead.
func (*ExtensionSetting) Descriptor() ([]byte, []int) {
	return file_proto_extension_model_proto_rawDescGZIP(), []int{24}
}

func (x *ExtensionSetting) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExtensionSetting) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ExtensionSetting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExtensionSetting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExtensionSetting) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *ExtensionSetting) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ExtensionSetting) GetType() ExtensionSettingType {
	if x != nil {
		return x.Type
	}
	return ExtensionSettingType_input
}

func (x *ExtensionSetting) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ExtensionSetting) GetOptions() string {
	if x != nil && x.Options != nil {
		return *x.Options
	}
	return ""
}

var File_proto_extension_model_proto protoreflect.FileDescriptor

const file_proto_extension_model_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/extension_model.proto\x12\x04miru\"\xe5\x01\n" +
	"\x11ExtensionListItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12\x16\n" +
	"\x06update\x18\x04 \x01(\tR\x06update\x12>\n" +
	"\aheaders\x18\x05 \x03(\v2$.miru.ExtensionListItem.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\fFilterOption\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"\xc9\x01\n" +
	"\fSelectFilter\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\adefault\x18\x02 \x01(\tR\adefault\x129\n" +
	"\aoptions\x18\x03 \x03(\v2\x1f.miru.SelectFilter.OptionsEntryR\aoptions\x1aN\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.miru.FilterOptionR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x11MultiSelectFilter\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\x12\x18\n" +
	"\adefault\x18\x04 \x03(\tR\adefault\x12>\n" +
	"\aoptions\x18\x05 \x03(\v2$.miru.MultiSelectFilter.OptionsEntryR\aoptions\x1aN\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.miru.FilterOptionR\x05value:\x028\x01\"\x89\x01\n" +
	"\vRangeFilter\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\x12\x1f\n" +
	"\vdefault_min\x18\x04 \x01(\x05R\n" +
	"defaultMin\x12\x1f\n" +
	"\vdefault_max\x18\x05 \x01(\x05R\n" +
	"defaultMax\"\xb0\x01\n" +
	"\x0fExtensionFilter\x12,\n" +
	"\x06select\x18\x01 \x01(\v2\x12.miru.SelectFilterH\x00R\x06select\x12<\n" +
	"\fmulti_select\x18\x02 \x01(\v2\x17.miru.MultiSelectFilterH\x00R\vmultiSelect\x12)\n" +
	"\x05range\x18\x03 \x01(\v2\x11.miru.RangeFilterH\x00R\x05rangeB\x06\n" +
	"\x04kind\"\xb0\x02\n" +
	"\x0fExtensionDetail\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x19\n" +
	"\x05cover\x18\x02 \x01(\tH\x01R\x05cover\x88\x01\x01\x12\x17\n" +
	"\x04desc\x18\x03 \x01(\tH\x02R\x04desc\x88\x01\x01\x127\n" +
	"\bepisodes\x18\x04 \x03(\v2\x1b.miru.ExtensionEpisodeGroupR\bepisodes\x12<\n" +
	"\aheaders\x18\x05 \x03(\v2\".miru.ExtensionDetail.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_titleB\b\n" +
	"\x06_coverB\a\n" +
	"\x05_desc\"Y\n" +
	"\x15ExtensionEpisodeGroup\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12*\n" +
	"\x04urls\x18\x02 \x03(\v2\x16.miru.ExtensionEpisodeR\x04urls\"\x87\x01\n" +
	"\x10ExtensionEpisode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06update\x18\x03 \x01(\tR\x06update\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\xb1\x01\n" +
	"\x0fExtensionMirror\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12<\n" +
	"\aheaders\x18\x03 \x03(\v2\".miru.ExtensionMirror.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x14ExtensionMirrorGroup\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12/\n" +
	"\amirrors\x18\x02 \x03(\v2\x15.miru.ExtensionMirrorR\amirrors\"u\n" +
	"\x1dExtensionBangumiWatchSubtitle\x12\x1f\n" +
	"\blanguage\x18\x01 \x01(\tH\x00R\blanguage\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03urlB\v\n" +
	"\t_language\"b\n" +
	"(ExtensionBangumiWatchTorrentFileTreeFile\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\x12\x1e\n" +
	"\n" +
	"piecesRoot\x18\x02 \x01(\tR\n" +
	"piecesRoot\"\x95\x02\n" +
	"$ExtensionBangumiWatchTorrentFileTree\x12B\n" +
	"\x04file\x18\x01 \x01(\v2..miru.ExtensionBangumiWatchTorrentFileTreeFileR\x04file\x12E\n" +
	"\x03dir\x18\x02 \x03(\v23.miru.ExtensionBangumiWatchTorrentFileTree.DirEntryR\x03dir\x1ab\n" +
	"\bDirEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.miru.ExtensionBangumiWatchTorrentFileTreeR\x05value:\x028\x01\"\xa2\x03\n" +
	"\"ExtensionBangumiWatchTorrentDetail\x12%\n" +
	"\vpieceLength\x18\x01 \x01(\x05H\x00R\vpieceLength\x88\x01\x01\x12\x1b\n" +
	"\x06pieces\x18\x02 \x01(\tH\x01R\x06pieces\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bnameUtf8\x18\x04 \x01(\tH\x03R\bnameUtf8\x88\x01\x01\x12\x1b\n" +
	"\x06length\x18\x05 \x01(\x03H\x04R\x06length\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x06 \x01(\tH\x05R\x06source\x88\x01\x01\x12%\n" +
	"\vmetaVersion\x18\a \x01(\x05H\x06R\vmetaVersion\x88\x01\x01\x12F\n" +
	"\bfileTree\x18\b \x01(\v2*.miru.ExtensionBangumiWatchTorrentFileTreeR\bfileTreeB\x0e\n" +
	"\f_pieceLengthB\t\n" +
	"\a_piecesB\a\n" +
	"\x05_nameB\v\n" +
	"\t_nameUtf8B\t\n" +
	"\a_lengthB\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_metaVersion\"\x92\x01\n" +
	"\x1cExtensionBangumiWatchTorrent\x12\x1a\n" +
	"\binfoHash\x18\x01 \x01(\tR\binfoHash\x12@\n" +
	"\x06detail\x18\x02 \x01(\v2(.miru.ExtensionBangumiWatchTorrentDetailR\x06detail\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\"\xf2\x02\n" +
	"\x15ExtensionBangumiWatch\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12A\n" +
	"\tsubtitles\x18\x03 \x03(\v2#.miru.ExtensionBangumiWatchSubtitleR\tsubtitles\x12B\n" +
	"\aheaders\x18\x04 \x03(\v2(.miru.ExtensionBangumiWatch.HeadersEntryR\aheaders\x12#\n" +
	"\n" +
	"audioTrack\x18\x05 \x01(\tH\x00R\n" +
	"audioTrack\x88\x01\x01\x12<\n" +
	"\atorrent\x18\x06 \x01(\v2\".miru.ExtensionBangumiWatchTorrentR\atorrent\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_audioTrack\"\xa7\x01\n" +
	"\x13ExtensionMangaWatch\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12@\n" +
	"\aheaders\x18\x02 \x03(\v2&.miru.ExtensionMangaWatch.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\x16ExtensionFikushonWatch\x12\x18\n" +
	"\acontent\x18\x01 \x03(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\bsubtitle\x18\x03 \x01(\tH\x00R\bsubtitle\x88\x01\x01B\v\n" +
	"\t_subtitle\"\xb5\x01\n" +
	"\x11ExtensionAllWatch\x12/\n" +
	"\x05manga\x18\x01 \x01(\v2\x19.miru.ExtensionMangaWatchR\x05manga\x128\n" +
	"\bfikushon\x18\x02 \x01(\v2\x1c.miru.ExtensionFikushonWatchR\bfikushon\x125\n" +
	"\abangumi\x18\x03 \x01(\v2\x1b.miru.ExtensionBangumiWatchR\abangumi\"\xbc\x01\n" +
	"\x0eExtensionWatch\x122\n" +
	"\x06groups\x18\x01 \x03(\v2\x1a.miru.ExtensionMirrorGroupR\x06groups\x12(\n" +
	"\rdefault_group\x18\x02 \x01(\tH\x00R\fdefaultGroup\x88\x01\x01\x12(\n" +
	"\rdefault_index\x18\x03 \x01(\x05H\x01R\fdefaultIndex\x88\x01\x01B\x10\n" +
	"\x0e_default_groupB\x10\n" +
	"\x0e_default_index\"\xce\x02\n" +
	"\x0fGithubExtension\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x17\n" +
	"\x04icon\x18\x06 \x01(\tH\x01R\x04icon\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04lang\x18\b \x01(\tR\x04lang\x12\x18\n" +
	"\awebSite\x18\t \x01(\tR\awebSite\x12\x12\n" +
	"\x04nsfw\x18\n" +
	" \x01(\bR\x04nsfw\x12\x18\n" +
	"\apackage\x18\v \x01(\tR\apackage\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tagsB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_icon\"l\n" +
	"\rExtensionRepo\x125\n" +
	"\n" +
	"extensions\x18\x01 \x03(\v2\x15.miru.GithubExtensionR\n" +
	"extensions\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"D\n" +
	"\n" +
	"RepoConfig\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\"\xbf\x02\n" +
	"\x10ExtensionSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x19\n" +
	"\x05value\x18\x05 \x01(\tH\x00R\x05value\x88\x01\x01\x12\"\n" +
	"\fdefaultValue\x18\x06 \x01(\tR\fdefaultValue\x12.\n" +
	"\x04type\x18\a \x01(\x0e2\x1a.miru.ExtensionSettingTypeR\x04type\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aoptions\x18\t \x01(\tH\x02R\aoptions\x88\x01\x01B\b\n" +
	"\x06_valueB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_options*8\n" +
	"\x14ExtensionSettingType\x12\t\n" +
	"\x05input\x10\x00\x12\t\n" +
	"\x05radio\x10\x01\x12\n" +
	"\n" +
	"\x06toggle\x10\x02B)Z'github.com/miru-project/miru-core/protob\x06proto3"

var (
	file_proto_extension_model_proto_rawDescOnce sync.Once
	file_proto_extension_model_proto_rawDescData []byte
)

func file_proto_extension_model_proto_rawDescGZIP() []byte {
	file_proto_extension_model_proto_rawDescOnce.Do(func() {
		file_proto_extension_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_extension_model_proto_rawDesc), len(file_proto_extension_model_proto_rawDesc)))
	})
	return file_proto_extension_model_proto_rawDescData
}

var file_proto_extension_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_extension_model_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_extension_model_proto_goTypes = []any{
	(ExtensionSettingType)(0),                        // 0: miru.ExtensionSettingType
	(*ExtensionListItem)(nil),                        // 1: miru.ExtensionListItem
	(*FilterOption)(nil),                             // 2: miru.FilterOption
	(*SelectFilter)(nil),                             // 3: miru.SelectFilter
	(*MultiSelectFilter)(nil),                        // 4: miru.MultiSelectFilter
	(*RangeFilter)(nil),                              // 5: miru.RangeFilter
	(*ExtensionFilter)(nil),                          // 6: miru.ExtensionFilter
	(*ExtensionDetail)(nil),                          // 7: miru.ExtensionDetail
	(*ExtensionEpisodeGroup)(nil),                    // 8: miru.ExtensionEpisodeGroup
	(*ExtensionEpisode)(nil),                         // 9: miru.ExtensionEpisode
	(*ExtensionMirror)(nil),                          // 10: miru.ExtensionMirror
	(*ExtensionMirrorGroup)(nil),                     // 11: miru.ExtensionMirrorGroup
	(*ExtensionBangumiWatchSubtitle)(nil),            // 12: miru.ExtensionBangumiWatchSubtitle
	(*ExtensionBangumiWatchTorrentFileTreeFile)(nil), // 13: miru.ExtensionBangumiWatchTorrentFileTreeFile
	(*ExtensionBangumiWatchTorrentFileTree)(nil),     // 14: miru.ExtensionBangumiWatchTorrentFileTree
	(*ExtensionBangumiWatchTorrentDetail)(nil),       // 15: miru.ExtensionBangumiWatchTorrentDetail
	(*ExtensionBangumiWatchTorrent)(nil),             // 16: miru.ExtensionBangumiWatchTorrent
	(*ExtensionBangumiWatch)(nil),                    // 17: miru.ExtensionBangumiWatch
	(*ExtensionMangaWatch)(nil),                      // 18: miru.ExtensionMangaWatch
	(*ExtensionFikushonWatch)(nil),                   // 19: miru.ExtensionFikushonWatch
	(*ExtensionAllWatch)(nil),                        // 20: miru.ExtensionAllWatch
	(*ExtensionWatch)(nil),                           // 21: miru.ExtensionWatch
	(*GithubExtension)(nil),                          // 22: miru.GithubExtension
	(*ExtensionRepo)(nil),                            // 23: miru.ExtensionRepo
	(*RepoConfig)(nil),                               // 24: miru.RepoConfig
	(*ExtensionSetting)(nil),                         // 25: miru.ExtensionSetting
	nil,                                              // 26: miru.ExtensionListItem.HeadersEntry
	nil,                                              // 27: miru.SelectFilter.OptionsEntry
	nil,                                              // 28: miru.MultiSelectFilter.OptionsEntry
	nil,                                              // 29: miru.ExtensionDetail.HeadersEntry
	nil,                                              // 30: miru.ExtensionMirror.HeadersEntry
	nil,                                              // 31: miru.ExtensionBangumiWatchTorrentFileTree.DirEntry
	nil,                                              // 32: miru.ExtensionBangumiWatch.HeadersEntry
	nil,                                              // 33: miru.ExtensionMangaWatch.HeadersEntry
}
var file_proto_extension_model_proto_depIdxs = []int32{
	26, // 0: miru.ExtensionListItem.headers:type_name -> miru.ExtensionListItem.HeadersEntry
	27, // 1: miru.SelectFilter.options:type_name -> miru.SelectFilter.OptionsEntry
	28, // 2: miru.MultiSelectFilter.options:type_name -> miru.MultiSelectFilter.OptionsEntry
	3,  // 3: miru.ExtensionFilter.select:type_name -> miru.SelectFilter
	4,  // 4: miru.ExtensionFilter.multi_select:type_name -> miru.MultiSelectFilter
	5,  // 5: miru.ExtensionFilter.range:type_name -> miru.RangeFilter
	8,  // 6: miru.ExtensionDetail.episodes:type_name -> miru.ExtensionEpisodeGroup
	29, // 7: miru.ExtensionDetail.headers:type_name -> miru.ExtensionDetail.HeadersEntry
	9,  // 8: miru.ExtensionEpisodeGroup.urls:type_name -> miru.ExtensionEpisode
	30, // 9: miru.ExtensionMirror.headers:type_name -> miru.ExtensionMirror.HeadersEntry
	10, // 10: miru.ExtensionMirrorGroup.mirrors:type_name -> miru.ExtensionMirror
	13, // 11: miru.ExtensionBangumiWatchTorrentFileTree.file:type_name -> miru.ExtensionBangumiWatchTorrentFileTreeFile
	31, // 12: miru.ExtensionBangumiWatchTorrentFileTree.dir:type_name -> miru.ExtensionBangumiWatchTorrentFileTree.DirEntry
	14, // 13: miru.ExtensionBangumiWatchTorrentDetail.fileTree:type_name -> miru.ExtensionBangumiWatchTorrentFileTree
	15, // 14: miru.ExtensionBangumiWatchTorrent.detail:type_name -> miru.ExtensionBangumiWatchTorrentDetail
	12, // 15: miru.ExtensionBangumiWatch.subtitles:type_name -> miru.ExtensionBangumiWatchSubtitle
	32, // 16: miru.ExtensionBangumiWatch.headers:type_name -> miru.ExtensionBangumiWatch.HeadersEntry
	16, // 17: miru.ExtensionBangumiWatch.torrent:type_name -> miru.ExtensionBangumiWatchTorrent
	33, // 18: miru.ExtensionMangaWatch.headers:type_name -> miru.ExtensionMangaWatch.HeadersEntry
	18, // 19: miru.ExtensionAllWatch.manga:type_name -> miru.ExtensionMangaWatch
	19, // 20: miru.ExtensionAllWatch.fikushon:type_name -> miru.ExtensionFikushonWatch
	17, // 21: miru.ExtensionAllWatch.bangumi:type_name -> miru.ExtensionBangumiWatch
	11, // 22: miru.ExtensionWatch.groups:type_name -> miru.ExtensionMirrorGroup
	22, // 23: miru.ExtensionRepo.extensions:type_name -> miru.GithubExtension
	0,  // 24: miru.ExtensionSetting.type:type_name -> miru.ExtensionSettingType
	2,  // 25: miru.SelectFilter.OptionsEntry.value:type_name -> miru.FilterOption
	2,  // 26: miru.MultiSelectFilter.OptionsEntry.value:type_name -> miru.FilterOption
	14, // 27: miru.ExtensionBangumiWatchTorrentFileTree.DirEntry.value:type_name -> miru.ExtensionBangumiWatchTorrentFileTree
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_extension_model_proto_init() }
func file_proto_extension_model_proto_init() {
	if File_proto_extension_model_proto != nil {
		return
	}
	file_proto_extension_model_proto_msgTypes[5].OneofWrappers = []any{
		(*ExtensionFilter_Select)(nil),
		(*ExtensionFilter_MultiSelect)(nil),
		(*ExtensionFilter_Range)(nil),
	}
	file_proto_extension_model_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[18].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[20].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[21].OneofWrappers = []any{}
	file_proto_extension_model_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_extension_model_proto_rawDesc), len(file_proto_extension_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_extension_model_proto_goTypes,
		DependencyIndexes: file_proto_extension_model_proto_depIdxs,
		EnumInfos:         file_proto_extension_model_proto_enumTypes,
		MessageInfos:      file_proto_extension_model_proto_msgTypes,
	}.Build()
	File_proto_extension_model_proto = out.File
	file_proto_extension_model_proto_goTypes = nil
	file_proto_extension_model_proto_depIdxs = nil
}
